# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8
PYTHON_COMPAT=( python3_14 )
DISTUTILS_SINGLE_IMPL=python3_14
DISTUTILS_USE_PEP517=setuptools
PYPI_NO_NORMALIZE=1
PYPI_PN="homeassistant"
inherit distutils-r1 pypi readme.gentoo-r1 systemd

MY_PN=homeassistant

if [[ ${PV} == *9999* ]]; then
	inherit git-r3
	EGIT_REPO_URI="https://github.com/home-assistant/core.git"
	EGIT_BRANCH="dev"
	S="${WORKDIR}/homeassistant-full-9999/"
else
	MY_PV=${PV/_beta/b}
	MY_P=${MY_PN}-${MY_PV}
	SRC_URI="$(pypi_sdist_url homeassistant)
	https://github.com/home-assistant/core/archive/${MY_PV}.tar.gz -> ${MY_P}.gh.tar.gz"
fi

DESCRIPTION="Open-source home automation platform running on Python."
HOMEPAGE="https://home-assistant.io/ https://git.edevau.net/onkelbeh/HomeAssistantRepository/"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="amd64 arm arm64 x86"
IUSE="bh1750 blinkt bme280 bme680 cli dht http mariadb mosquitto mysql smarthab socat somfy ssl systemd tesla wink  abode acaia accuweather acer-projector acmeda actron-air adax adguard ads advantage-air aemet aftership agent-dvr airgradient airly airnow airobot airos airpatrol airq airthings-ble airthings airtouch4 airtouch5 airvisual airvisual-pro airzone-cloud airzone aladdin-connect alarmdecoder alexa-devices alpha-vantage altruist amazon-polly amberelectric ambient-network ambient-station amcrest ampio analytics-insights android-ip-webcam androidtv androidtv-remote anel-pwrctrl anglian-water anova anthemav anthropic aosmith apache-kafka apcupsd apple-tv apprise aprilaire aprs apsystems aquacell aqualogic aquostv aranet arcam-fmj arris-tg2492lg aruba arve aseko-pool-live assist-pipeline assist-satellite asuswrt atag aten-pe atome august aurora-abb-powerone aurora aussie-broadband autarco avea avion awair aws aws-s3 axis azure-data-explorer azure-devops azure-event-hub azure-service-bus azure-storage backblaze-b2 backup baf baidu balboa bang-olufsen bbox beewi-smartclim bitcoin bizkaibus blackbird blebox blink blockchain blue-current bluemaestro bluesound bluetooth bmw-connected-drive bond bosch-alarm bosch-shc braviatv bring broadlink brother brottsplatskartan brunt bryant-evolution bsblan bt-home-hub-5 bthome bt-smarthub buienradar caldav cambridge-audio camera canary cast ccm15 chacon-dio channels cisco-ios cisco-mobility-express cisco-webex-teams citybikes clementine cloudflare cloudflare-r2 cloud cmus co2signal coinbase color-extractor comelit comfoconnect command-line compensation compit concord232 control4 conversation cookidoo coolmaster cppm-tracker cpuspeed crownstone cync daikin danfoss-air datadog deako debugpy deconz decora-wifi delijn deluge denonavr devialet devolo-home-control devolo-home-network dexcom dhcp digital-ocean directv discogs discord discovergy dlink dlna-dmr dlna-dms dnsip doods doorbird dormakaba-dkey dremel-3d-printer drop-connect droplet dsmr duke-energy dunehd duotecno dwd-weather-warnings dynalite eafm easyenergy ebox ebusd ecoal-boiler ecobee ecoforest econet ecovacs ecowitt edimax edl21 efergy egardia egauge eheimdigital ekeybionyx electrasmart electric-kiwi elevenlabs elgato eliqonline elkm1 elmax elvia elv emby emoncms-history emoncms emonitor emulated-kasa emulated-roku energenie-power-sockets energyid energyzero enigma2 enocean enphase-envoy entur-public-transport environment-canada envisalink ephember epic-games-store epion epson eq3btsmart escea esphome essent etherscan eufylife-ble eufy everlights evil-genius-labs evohome ezviz faa-delays familyhub fastdotcom feedreader ffmpeg fibaro fido file fing fints firefly-iii fireservicerota firmata fish-audio fitbit fivem fixer fjaraskupan fleetgo flexit-bacnet flic flipr flo flume fluss flux-led folder-watcher foobot forecast-solar forked-daapd fortios foscam freebox freedompro free-mobile fressnapf-tracker fritzbox-callmonitor fritzbox fritz fronius frontend frontier-silicon fujitsu-fglair fully-kiosk futurenow fyta garages-amsterdam gardena-bluetooth gc100 gdacs generic geniushub gentex-homelink geocaching geo-json-events geonetnz-quakes geonetnz-volcano geo-rss-events ghost gios github gitlab-ci gitter glances go2rtc goalzero gogogate2 goodwe google-air-quality google-assistant-sdk google-cloud google-drive google-generative-ai-conversation google-mail google google-maps google-photos google-pubsub google-sheets google-tasks google-translate google-travel-time google-weather govee-ble govee-light-local gpsd gree greeneye-monitor green-planet-energy greenwave growatt-server gtfs guardian habitica hanna hardware harman-kardon-avr harmony hassio hdfury hdmi-cec heatmiser hegel heos here-travel-time hikvisioncam hikvision hisense-aehw4a1 hive hko hlk-sw16 holiday homeassistant-hardware home-connect homee homekit-controller homekit homematicip-cloud homematic homevolt homewizard homeworks honeywell horizon hp-ilo html5 huawei-lte hue-ble hue huisbaasje hunterdouglas-powerview husqvarna-automower-ble husqvarna-automower huum hvv-departures hydrawise hyperion hypontech ialarm iammeter iaqualink ibeacon icloud idasen-desk idrive-e2 idteck-prox ifttt iglo igloohome ign-sismologia ihc image-upload imap imeon-inverter imgw-pib immich improv-ble incomfort indevolt inels influxdb inkbird insteon intelliclima intellifire intesishome iometer iotawatt iotty iperf3 ipma ipp iqvia irish-rail-transport irm-kmi iron-os isal iskra islamic-prayer-times israel-rail iss ista-ecotrend isy994 itach ituran izone jellyfin jewish-calendar joaoapps-join justnimbus jvc-projector kaiterra kaleidescape keba keenetic-ndms2 kef kegtron keyboard-remote keymitt-ble kira kiwi kmtronic knocki knx kodi konnected kostal-plenticore kraken kulersky kwb lacrosse lacrosse-view lamarzocco lametric landisgyr-heat-meter lastfm launch-library laundrify lcn ld2410-ble leaone led-ble lektrico letpot lg-netcast lg-soundbar lg-thinq libre-hardware-monitor lidarr liebherr lifx lightwave limitlessled linkplay linode linux-battery litejet litterrobot livisi local-calendar local-todo london-underground lookin loqed luci luftdaten lunatone lupusec lutron-caseta lutron lw12wifi lyric madvr mailgun marytts mastodon matrix matter maxcube mcp mcp-server mealie meater medcom-ble media-extractor mediaroom melcloud melissa melnor message-bird met-eireann meteoalarm meteoclimatic meteo-france meteo-lt met metoffice mfi microbees microsoft miele mikrotik mill minecraft-server minio moat mobile-app mochad modbus modem-callerid modern-forms moehlenhoff-alpha2 monarch-money monoprice monzo mopeka motionblinds-ble motion-blinds motioneye motionmount mpd mqtt msteams mta mullvad music-assistant mutesync mvglive myneomitis mysensors mystrom mythicbeastsdns myuplink nad nam nanoleaf nasweb neato nederlandse-spoorwegen ness-alarm nest netatmo netdata netgear-lte netgear netio network neurio-energy nexia nextbus nextcloud nextdns nfandroidtv nibe-heatpump nice-go nightscout niko-home-control nilu nina nintendo-parental-controls nissan-leaf nmap-tracker nmbs noaa-tides nobo-hub nordpool norway-air notify-events notion nrgkick nsw-fuel-station nsw-rural-fire-service-feed ntfy nuheat nuki numato nut nws nx584 nyt-games nzbget oasa-telematics obihai octoprint oem ohmconnect ohme ollama ombi omnilogic ondilo-ico onedrive-for-business onedrive onewire onkyo onvif openai-conversation openerz openevse openexchangerates opengarage openhome open-meteo openrgb open-router opensensemap opensky opentherm-gw openuv openweathermap opnsense opower opple oralb oru orvibo osoenergy osramlightify otbr otp ourgroceries overkiz overseerr ovo-energy owntracks p1-monitor palazzetti panasonic-bluray panasonic-viera paperless-ngx peblar peco pegel-online pencom permobil pglab philips-js picnic pi-hole pilight ping pjlink plaato playstation-network plex plugwise pocketcasts point pooldose poolsense portainer powerfox-local powerfox powerwall prana private-ble-device probe-plus profiler progettihwsw proliphix prometheus prosegur prowl proxmoxve proxy prusalink ps4 pterodactyl pulseaudio-loopback pure-energie purpleair pushbullet pushover pvoutput pvpc-hourly-pricing pyload python-script qbittorrent qbus qingping qld-bushfire qnap qnap-qsw qrcode quantum-gateway qvr-pro qwikswitch rabbitair rachio radarr radio-browser radiotherm rainbird raincloud rainforest-eagle rainforest-raven rainmachine rapt-ble raspyrfm rdw recollect-waste recorder recswitch reddit redgtech refoss rehlko rejseplanen remember-the-milk remote-calendar remote-rpi-gpio renault renson reolink repetier rest rflink rfxtrx ridwell ring ripple risco rituals-perfume-genie rmvtransport roborock rocketchat roku romy roomba roon route53 route-b-smart-meter rova rpi-power ruckus-unleashed russound-rio russound-rnet +ruuvi-gateway ruuvitag-ble rympro sabnzbd saj samsungtv sanix satel-integra saunum schlage schluter scrape screenlogic scsgate season sendgrid sense sensibo sensirion-ble sensorpro sensorpush-cloud sensorpush sensoterra sentry senz serial serial-pm sesame seven-segments seventeentrack sfr-box sftp-storage sharkiq +shelly shodan sia sighthound signal-messenger simplefin simplepush simplisafe sinch sisyphus skybeacon skybell sky-hub sky-remote slack sleepiq slide-local slide slimproto sma smappee smarla smart-meter-texas smartthings smarttub smarty smhi smlight snapcast snmp snoo snooz solaredge-local solaredge solarlog solax soma somfy-mylink sonarr songpal sonos sony-projector soundtouch spc speedtestdotnet splunk spotify sql squeezebox srp-energy ssdp starline starlingbank starlink startca statsd steamist steam-online stiebel-eltron stookwijzer streamlabswater stream subaru suez-water sunricher-dali supla surepetcare swiss-hydrological-data swiss-public-transport switchbee switchbot-cloud switchbot switcher-kis switchmate syncthing syncthru synology-dsm synology-srm system-bridge systemmonitor systemnexa2 tado tailscale tailwind tami4 tankerkoenig tank-utility tapsaff tasmota tautulli technove ted5000 tedee telegram-bot tellduslive tellstick teltonika temper tesla-fleet tesla-wall-connector teslemetry tessie thermobeacon thermopro thethingsnetwork thingspeak thinkingcleaner thread tibber tikteck tile tilt-ble tilt-pi tmb todoist togrill tolo tomorrowio toon totalconnect touchline touchline-sl tplink-lte tplink tplink-omada traccar traccar-server tractive tradfri trafikverket-camera trafikverket-ferry trafikverket-train trafikverket-weatherstation trane transmission transport-nsw travisci trend triggercmd tts tuya twentemilieu twilio twinkly twitch twitter ubus uhoo ukraine-alarm unifi-direct unifiled unifi unifiprotect upb upc-connect upcloud upnp uptime-kuma uptimerobot usb usgs-earthquakes-feed utility-meter uvc v2c vallox vasttrafik vegehub velbus velux venstar vera verisure versasense version vesync viaggiatreno vicare victron-ble victron-remote-monitoring vilfo vivotek vizio vlc vlc-telnet vodafone-station voip volkszaehler volumio volvo w800rf32 wake-on-lan wallbox waqi waterfurnace watergate watts watttime waze-travel-time weatherflow-cloud weatherflow weatherkit webdav webmin webostv weheat wemo whirlpool whois wiffi wilight wirelesstag withings wiz wled wmspro wolflink workday ws66i wsdot wyoming xbox xeoma xiaomi-aqara xiaomi-ble xiaomi-miio xiaomi-tv xmpp xs1 yale yale-smart-alarm yalexs-ble yamaha yamaha-musiccast yandex-transport yardian yeelight yeelightsunflower yi yolink youless youtube zabbix zamg zeroconf zerproc zestimate zeversolar zha zhong-hong ziggo-mediabox-xl zimi zinvolt zoneminder zwave-js zwave-me blinkt bme280 bme680 cli dht mariadb mosquitto smarthab socat tesla wink"
RESTRICT="!test? ( test )"

# external deps
RDEPEND="${PYTHON_DEPS} acct-group/${MY_PN} acct-user/${MY_PN}
	dev-lang/python:3.14
	app-admin/logrotate
	dev-db/sqlite
	dev-libs/libfastjson
	dev-libs/xerces-c"
REQUIRED_USE="bluetooth? ( ruuvi-gateway shelly )
	homekit-controller? ( bluetooth )"
# Home Assistant Core dependencies from /var/tmp/portage/app-misc/homeassistant-2026.3.2/work/core-2026.3.2/homeassistant/package_constraints.txt
RDEPEND="${RDEPEND}

	~dev-python/aiodhcpwatcher-1.2.1
	~dev-python/aiodiscover-2.7.1
	~dev-python/aiodns-4.0.0
	~dev-python/aiogithubapi-26.0.0
	~dev-python/aiohasupervisor-0.3.3
	~dev-python/aiohttp-asyncmdnsresolver-0.1.1
	~dev-python/aiohttp-fast-zlib-0.3.0
	~dev-python/aiohttp-3.13.3
	~dev-python/aiohttp-cors-0.8.1
	~dev-python/aiousbwatcher-1.1.1
	~dev-python/aiozoneinfo-0.2.3
	~dev-python/annotatedyaml-1.0.2
	~dev-python/astral-2.2
	~dev-python/async-interrupt-1.2.2
	~dev-python/async-upnp-client-0.46.2
	~dev-python/atomicwrites-1.4.1
	~dev-python/attrs-25.4.0
	~dev-python/audioop-lts-0.2.1
	~dev-python/av-16.0.1
	~dev-python/awesomeversion-25.8.0
	~dev-python/bcrypt-5.0.0
	~dev-python/bleak-retry-connector-4.4.3
	~dev-python/bleak-2.1.1
	~dev-python/bluetooth-adapters-2.1.0
	~dev-python/bluetooth-auto-recovery-1.5.3
	~dev-python/bluetooth-data-tools-1.28.4
	~dev-python/cached-ipaddress-1.0.1
	>=dev-python/certifi-2021.5.30
	~dev-python/ciso8601-2.3.3
	~dev-python/cronsim-2.7
	~dev-python/cryptography-46.0.5
	~dev-python/dbus-fast-3.1.2
	~dev-python/file-read-backwards-2.0.0
	~dev-python/fnv-hash-fast-1.6.0
	~dev-python/go2rtc-client-0.4.0
	~dev-python/ha-ffmpeg-3.2.2
	~dev-python/habluetooth-5.8.0
	~dev-python/hass-nabucasa-1.15.0
	~dev-python/hassil-3.5.0
	~dev-python/home-assistant-bluetooth-1.13.1
	~dev-python/home-assistant-frontend-20260312.0
	~dev-python/home-assistant-intents-2026.3.3
	~dev-python/httpx-0.28.1
	~dev-python/ifaddr-0.2.0
	~dev-python/jinja2-3.1.6
	~dev-python/lru-dict-1.3.0
	~media-libs/mutagen-1.47.0
	~dev-python/openai-2.21.0
	~dev-python/orjson-3.11.7
	>=dev-python/packaging-23.1
	~dev-python/paho-mqtt-2.1.0
	~dev-python/pillow-12.1.1
	~dev-python/propcache-0.4.1
	~dev-python/psutil-home-assistant-0.0.1
	~dev-python/pyjwt-2.10.1
	~dev-python/pymicro-vad-1.0.1
	~dev-python/pynacl-1.6.2
	~dev-python/pyopenssl-25.3.0
	~dev-python/pyserial-3.5
	~dev-python/pyspeex-noise-1.0.2
	~dev-python/python-slugify-8.0.4
	~dev-python/pyturbojpeg-1.8.0
	~dev-python/pyyaml-6.0.3
	~dev-python/requests-2.32.5
	~dev-python/securetar-2026.2.0
	~dev-python/sqlalchemy-2.0.41
	~dev-python/standard-aifc-3.13.0
	~dev-python/standard-telnetlib-3.13.0
	>=dev-python/typing-extensions-4.15.0
	~dev-python/ulid-transform-1.5.2
	>=dev-python/urllib3-2.0
	>=dev-python/uv-0.10.6

	~dev-python/voluptuous-openapi-0.2.0
	~dev-python/voluptuous-serialize-2.7.0
	~dev-python/voluptuous-0.16.0
	~dev-python/webrtc-models-0.3.0
	~dev-python/yarl-1.22.0
	~dev-python/zeroconf-0.148.0
	>=dev-python/pycryptodome-3.6.6
	>=dev-python/httplib2-0.19.0
	~dev-python/grpcio-1.78.0
	~dev-python/grpcio-status-1.78.0
	~dev-python/grpcio-reflection-1.78.0
	>=dev-python/btlewrap-0.0.10
	~dev-python/anyio-4.10.0
	~dev-python/h11-0.16.0
	~dev-python/httpcore-1.0.9
	>=dev-python/hyperframe-5.2.0
	~dev-python/numpy-2.3.2
	~dev-python/pandas-2.3.3
	>=dev-python/multidict-6.0.2
	>=dev-python/backoff-2.0
	>=app-arch/brotli-1.2.0
	~dev-python/pydantic-2.12.2
	>=dev-python/mashumaro-3.17
	~dev-python/protobuf-6.32.0
	>=dev-python/faust-cchardet-2.1.18
	>=dev-python/websockets-15.0.1
	~dev-python/charset-normalizer-3.4.3
	>=dev-python/dacite-1.7.0
	>=dev-python/chacha20poly1305-reuseable-0.13.0
	>=dev-python/pycountry-23.12.11
	>=net-analyzer/scapy-2.6.1
	>=dev-python/tuf-4.0.0
	~dev-python/async-timeout-4.0.3
	>=dev-python/aiofiles-24.1.0
	>=dev-python/multidict-6.4.2
	~dev-python/num2words-0.5.14
	~dev-python/pymodbus-3.11.2
	~dev-python/pytest-rerunfailures-16.0.1
	>=dev-python/aiomqtt-2.5.0
	<=dev-python/auth0-python-4.99"

# Module requirements from useflags
RDEPEND="${RDEPEND}
	bh1750? ( dev-python/i2csense )
	blinkt? ( ~dev-python/blinkt-0.1.0 )
	bme280? ( dev-python/i2csense dev-python/bme280spi )
	bme680? ( dev-python/bme680 )
	cli? ( app-misc/home-assistant-cli )
	dht? ( ~dev-python/adafruit-circuitpython-dht-3.7.0 ~dev-python/rpi-gpio-0.7.1_alpha4 )
	http? ( dev-python/aiohttp ~dev-python/aiohttp-fast-url-dispatcher-0.3.0 ~dev-python/aiohttp-zlib-ng-0.3.1 )
	mariadb? ( dev-python/mysqlclient )
	mosquitto? ( app-misc/mosquitto )
	mysql? ( dev-python/mysqlclient )
	smarthab? ( ~dev-python/smarthab-0.21 )
	socat? ( net-misc/socat )
	somfy? ( ~dev-python/pymfy-0.11.0 )
	ssl? ( dev-libs/openssl app-crypt/certbot net-proxy/haproxy )
	tesla? ( ~dev-python/teslajsonpy-0.18.3 )
	wink? ( ~dev-python/pubnubsub-handler-1.0.9 ~dev-python/python-wink-1.10.5 )
	abode? ( ~dev-python/jaraco-abode-6.2.1 )
	acaia? ( ~dev-python/aioacaia-0.1.17 )
	accuweather? ( ~dev-python/accuweather-5.1.0 )
	acer-projector? ( ~dev-python/pyserial-3.5 )
	acmeda? ( ~dev-python/aiopulse-0.4.6 )
	actron-air? ( ~dev-python/actron-neo-api-0.4.1 )
	adax? ( ~dev-python/adax-local-0.3.0 ~dev-python/adax-0.4.0 )
	adguard? ( ~dev-python/adguardhome-0.8.1 )
	ads? ( ~dev-python/pyads-3.4.0 )
	advantage-air? ( ~dev-python/advantage-air-0.4.4 )
	aemet? ( ~dev-python/aemet-opendata-0.6.4 )
	aftership? ( ~dev-python/pyaftership-21.11.0 )
	agent-dvr? ( ~dev-python/agent-py-0.0.24 )
	airgradient? ( ~dev-python/airgradient-0.9.2 )
	airly? ( ~dev-python/airly-1.1.0 )
	airnow? ( ~dev-python/pyairnow-1.3.1 )
	airobot? ( ~dev-python/pyairobotrest-0.3.0 )
	airos? ( ~dev-python/airos-0.6.4 )
	airpatrol? ( ~dev-python/airpatrol-0.1.0 )
	airq? ( ~dev-python/aioairq-0.4.7 )
	airthings-ble? ( ~dev-python/airthings-ble-1.2.0 )
	airthings? ( ~dev-python/airthings-cloud-0.2.0 )
	airtouch4? ( ~dev-python/airtouch4pyapi-1.0.5 )
	airtouch5? ( ~dev-python/airtouch5py-0.3.0 )
	airvisual? ( ~dev-python/pyairvisual-2023.8.1 )
	airvisual-pro? ( ~dev-python/pyairvisual-2023.8.1 )
	airzone-cloud? ( ~dev-python/aioairzone-cloud-0.7.2 )
	airzone? ( ~dev-python/aioairzone-1.0.5 )
	aladdin-connect? ( ~dev-python/genie-partner-sdk-1.0.11 )
	alarmdecoder? ( ~dev-python/adext-0.4.4 )
	alexa-devices? ( ~dev-python/aioamazondevices-13.0.1 )
	alpha-vantage? ( ~dev-python/alpha-vantage-2.3.1 )
	altruist? ( ~dev-python/altruistclient-0.1.1 )
	amazon-polly? ( ~dev-python/boto3-1.37.1 )
	amberelectric? ( ~dev-python/amberelectric-2.0.12 )
	ambient-network? ( ~dev-python/aioambient-2024.8.0 )
	ambient-station? ( ~dev-python/aioambient-2024.8.0 )
	amcrest? ( ~dev-python/amcrest-1.9.9 )
	ampio? ( ~dev-python/asmog-0.0.6 )
	analytics-insights? ( ~dev-python/python-homeassistant-analytics-0.9.0 )
	android-ip-webcam? ( ~dev-python/pydroid-ipcam-3.0.0 )
	androidtv? ( ~dev-python/adb-shell-0.4.4[async] ~dev-python/androidtv-0.0.75[async] )
	androidtv-remote? ( ~dev-python/androidtvremote2-0.2.3 )
	anel-pwrctrl? ( ~dev-python/anel-pwrctrl-homeassistant-0.0.1 )
	anglian-water? ( ~dev-python/pyanglianwater-3.1.1 )
	anova? ( ~dev-python/anova-wifi-0.17.0 )
	anthemav? ( ~dev-python/anthemav-1.4.1 )
	anthropic? ( ~dev-python/anthropic-0.83.0 )
	aosmith? ( ~dev-python/py-aosmith-1.0.17 )
	apache-kafka? ( ~dev-python/aiokafka-0.10.0 )
	apcupsd? ( ~dev-python/aioapcaccess-1.0.0 )
	apple-tv? ( ~dev-python/pyatv-0.17.0 )
	apprise? ( ~dev-python/apprise-1.9.1 )
	aprilaire? ( ~dev-python/pyaprilaire-0.9.1 )
	aprs? ( ~dev-python/aprslib-0.7.2 ~sci-geosciences/geopy-2.3.0 )
	apsystems? ( ~dev-python/apsystems-ez1-2.7.0 )
	aquacell? ( ~dev-python/aioaquacell-0.2.0 )
	aqualogic? ( ~dev-python/aqualogic-2.6 )
	aquostv? ( ~dev-python/sharp-aquos-rc-0.3.2 )
	aranet? ( ~dev-python/aranet4-2.6.0 )
	arcam-fmj? ( ~dev-python/arcam-fmj-1.8.2 )
	arris-tg2492lg? ( ~dev-python/arris-tg2492lg-2.2.0 )
	aruba? ( ~dev-python/pexpect-4.9.0 )
	arve? ( ~dev-python/asyncarve-0.1.1 )
	aseko-pool-live? ( ~dev-python/aioaseko-1.0.0 )
	assist-pipeline? ( ~dev-python/pymicro-vad-1.0.1 ~dev-python/pyspeex-noise-1.0.2 )
	assist-satellite? ( ~dev-python/hassil-3.5.0 )
	asuswrt? ( ~dev-python/aioasuswrt-1.5.4 ~dev-python/asusrouter-1.21.3 )
	atag? ( ~dev-python/pyatag-0.3.5.3 )
	aten-pe? ( ~dev-python/auroranoaa-0.0.5 )
	atome? ( ~dev-python/pyatome-0.1.1 )
	august? ( ~dev-python/yalexs-ble-3.2.8 ~dev-python/yalexs-9.2.0 )
	aurora-abb-powerone? ( ~dev-python/aurorapy-0.2.7 )
	aurora? ( ~dev-python/auroranoaa-0.0.5 )
	aussie-broadband? ( ~dev-python/pyaussiebb-0.1.5 )
	autarco? ( ~dev-python/autarco-3.2.0 )
	avea? ( ~dev-python/avea-1.6.1 )
	avion? ( ~dev-python/axis-66 )
	awair? ( ~dev-python/python-awair-0.2.5 )
	aws? ( ~dev-python/aiobotocore-2.21.1 ~dev-python/botocore-1.37.1 )
	aws-s3? ( ~dev-python/aiobotocore-2.21.1 )
	axis? ( ~dev-python/axis-66 )
	azure-data-explorer? ( ~dev-python/azure-kusto-data-4.5.1[aio] ~dev-python/azure-kusto-ingest-4.5.1 )
	azure-devops? ( ~dev-python/aioazuredevops-2.2.2 )
	azure-event-hub? ( ~dev-python/azure-eventhub-5.11.1 )
	azure-service-bus? ( ~dev-python/azure-servicebus-7.10.0 )
	azure-storage? ( ~dev-python/azure-storage-blob-12.24.0 )
	backblaze-b2? ( ~dev-python/b2sdk-2.10.1 )
	backup? ( ~dev-python/cronsim-2.7 ~dev-python/securetar-2026.2.0 )
	baf? ( ~dev-python/aiobafi6-0.9.0 )
	baidu? ( ~dev-python/baidu-aip-1.6.6.0 )
	balboa? ( ~dev-python/pybalboa-1.1.3 )
	bang-olufsen? ( ~dev-python/mozart-api-5.3.1.108.2 )
	bbox? ( ~dev-python/pybbox-0.0.5_alpha0 )
	beewi-smartclim? ( ~dev-python/bimmer-connected-0.17.3[china] )
	bitcoin? ( ~dev-python/blockchain-1.4.4 )
	bizkaibus? ( ~dev-python/bizkaibus-0.1.1 )
	blackbird? ( ~dev-python/pyblackbird-0.6 )
	blebox? ( ~dev-python/blebox-uniapi-2.5.0 )
	blink? ( ~dev-python/blinkpy-0.25.2 )
	blockchain? ( ~dev-python/python-blockchain-api-0.0.2 )
	blue-current? ( ~dev-python/bluecurrent-api-1.3.2 )
	bluemaestro? ( ~dev-python/bluemaestro-ble-0.4.1 )
	bluesound? ( ~dev-python/pyblu-2.0.5 )
	bluetooth? ( ~dev-python/bleak-retry-connector-4.4.3 ~dev-python/bleak-2.1.1 ~dev-python/bluetooth-adapters-2.1.0 ~dev-python/bluetooth-auto-recovery-1.5.3 ~dev-python/bluetooth-data-tools-1.28.4 ~dev-python/dbus-fast-3.1.2 ~dev-python/habluetooth-5.8.0 )
	bmw-connected-drive? ( ~dev-python/bimmer-connected-0.17.3[china] )
	bond? ( ~dev-python/bond-async-0.2.1 )
	bosch-alarm? ( ~dev-python/bosch-alarm-mode2-0.4.10 )
	bosch-shc? ( ~dev-python/boschshcpy-0.2.107 )
	braviatv? ( ~dev-python/pybravia-0.4.1 )
	bring? ( ~dev-python/bring-api-1.1.1 )
	broadlink? ( ~dev-python/broadlink-0.19.0 )
	brother? ( ~dev-python/brother-6.0.0 )
	brottsplatskartan? ( ~dev-python/brottsplatskartan-1.0.5 )
	brunt? ( ~dev-python/brunt-1.2.0 )
	bryant-evolution? ( ~dev-python/evolutionhttp-0.0.18 )
	bsblan? ( ~dev-python/python-bsblan-5.1.2 )
	bt-home-hub-5? ( ~dev-python/bthomehub5-devicelist-0.1.1 )
	bthome? ( ~dev-python/bthome-ble-3.17.0 )
	bt-smarthub? ( ~dev-python/btsmarthub-devicelist-0.2.3 )
	buienradar? ( ~dev-python/buienradar-1.0.6 )
	caldav? ( ~dev-python/caldav-2.1.0 ~dev-python/icalendar-6.3.1 ~dev-python/vobject-0.9.9 )
	cambridge-audio? ( ~dev-python/aiostreammagic-2.13.0 )
	camera? ( ~dev-python/pyturbojpeg-1.8.0 )
	canary? ( ~dev-python/py-canary-0.5.4 )
	cast? ( ~dev-python/pychromecast-14.0.10 )
	ccm15? ( ~dev-python/py-ccm15-0.1.2 )
	chacon-dio? ( ~dev-python/dio-chacon-wifi-api-1.2.2 )
	channels? ( ~dev-python/pychannels-1.2.3 )
	cisco-ios? ( ~dev-python/pexpect-4.9.0 )
	cisco-mobility-express? ( ~dev-python/ciscomobilityexpress-0.3.9 )
	cisco-webex-teams? ( ~dev-python/webexpythonsdk-2.0.1 )
	citybikes? ( ~dev-python/python-citybikes-0.3.3 )
	clementine? ( ~dev-python/python-clementine-remote-1.0.1 )
	cloudflare? ( ~dev-python/pycfdns-3.0.0 )
	cloudflare-r2? ( ~dev-python/aiobotocore-2.21.1 )
	cloud? ( ~dev-python/hass-nabucasa-1.15.0 ~dev-python/openai-2.21.0 )
	cmus? ( ~dev-python/pycmus-0.1.1 )
	co2signal? ( ~dev-python/aioelectricitymaps-1.1.1 )
	coinbase? ( ~dev-python/coinbase-advanced-py-1.2.2 )
	color-extractor? ( ~dev-python/colorthief-0.2.1 )
	comelit? ( ~dev-python/aiocomelit-2.0.1 )
	comfoconnect? ( ~dev-python/pycomfoconnect-0.5.1 )
	command-line? ( ~dev-python/jsonpath-0.82.2 )
	compensation? ( ~dev-python/numpy-2.3.2 )
	compit? ( ~dev-python/compit-inext-api-0.8.0 )
	concord232? ( ~dev-python/concord232-0.15.1 )
	control4? ( ~dev-python/pycontrol4-1.5.0 )
	conversation? ( ~dev-python/hassil-3.5.0 ~dev-python/home-assistant-intents-2026.3.3 )
	cookidoo? ( ~dev-python/cookidoo-api-0.14.0 )
	coolmaster? ( ~dev-python/pycoolmasternet-async-0.2.4 )
	cppm-tracker? ( ~dev-python/clearpasspy-1.0.2 )
	cpuspeed? ( ~dev-python/py-cpuinfo-9.0.0 )
	crownstone? ( ~dev-python/crownstone-cloud-1.4.11 ~dev-python/crownstone-sse-2.0.5 ~dev-python/crownstone-uart-2.1.0 ~dev-python/pyserial-3.5 )
	cync? ( ~dev-python/pycync-0.5.0 )
	daikin? ( ~dev-python/pydaikin-2.17.2 )
	danfoss-air? ( ~dev-python/pydanfossair-0.1.0 )
	datadog? ( ~dev-python/datadog-0.52.0 )
	deako? ( ~dev-python/pydeako-0.6.0 )
	debugpy? ( ~dev-python/debugpy-1.8.17 )
	deconz? ( ~dev-python/pydeconz-120 )
	decora-wifi? ( ~dev-python/decora-wifi-1.4 )
	delijn? ( ~dev-python/pydelijn-1.1.0 )
	deluge? ( ~dev-python/deluge-client-1.10.2 )
	denonavr? ( ~dev-python/denonavr-1.3.2 )
	devialet? ( ~dev-python/devialet-1.5.7 )
	devolo-home-control? ( ~dev-python/devolo-home-control-api-0.19.0 )
	devolo-home-network? ( ~dev-python/devolo-plc-api-1.5.1 )
	dexcom? ( ~dev-python/pydexcom-0.5.1 )
	dhcp? ( ~dev-python/aiodhcpwatcher-1.2.1 ~dev-python/aiodiscover-2.7.1 ~dev-python/cached-ipaddress-1.0.1 )
	digital-ocean? ( ~dev-python/python-digitalocean-1.13.2 )
	directv? ( ~dev-python/directv-0.4.0 )
	discogs? ( ~dev-python/discogs-client-2.3.0 )
	discord? ( ~dev-python/nextcord-3.1.0 )
	discovergy? ( ~dev-python/pydiscovergy-3.0.2 )
	dlink? ( ~dev-python/pyw215-0.8.0 )
	dlna-dmr? ( ~dev-python/async-upnp-client-0.46.2 ~dev-python/getmac-0.9.5 )
	dlna-dms? ( ~dev-python/async-upnp-client-0.46.2 )
	dnsip? ( ~dev-python/aiodns-4.0.0 )
	doods? ( ~dev-python/pillow-12.1.1 ~dev-python/pydoods-1.0.2 )
	doorbird? ( ~dev-python/doorbirdpy-3.0.11 )
	dormakaba-dkey? ( ~dev-python/py-dormakaba-dkey-1.0.6 )
	dremel-3d-printer? ( ~dev-python/dremel3dpy-2.1.1 )
	drop-connect? ( ~dev-python/dropmqttapi-1.0.3 )
	droplet? ( ~dev-python/pydroplet-2.3.4 )
	dsmr? ( ~dev-python/dsmr-parser-1.5.0 )
	duke-energy? ( ~dev-python/aiodukeenergy-0.3.0 )
	dunehd? ( ~dev-python/pdunehd-1.3.2 )
	duotecno? ( ~dev-python/pyduotecno-2024.10.1 )
	dwd-weather-warnings? ( ~dev-python/dwdwfsapi-1.0.7 )
	dynalite? ( ~dev-python/dynalite-devices-0.1.47 ~dev-python/dynalite-panel-0.0.4 )
	eafm? ( ~dev-python/aioeafm-0.1.2 )
	easyenergy? ( ~dev-python/easyenergy-2.2.0 )
	ebox? ( ~dev-python/pyebox-1.1.4 )
	ebusd? ( ~dev-python/ebusdpy-0.0.17 )
	ecoal-boiler? ( ~dev-python/ecoaliface-0.4.0 )
	ecobee? ( ~dev-python/python-ecobee-api-0.3.2 )
	ecoforest? ( ~dev-python/pyecoforest-0.4.0 )
	econet? ( ~dev-python/pyeconet-0.2.1 )
	ecovacs? ( ~dev-python/deebot-client-18.0.0 ~dev-python/py-sucks-0.9.11 )
	ecowitt? ( ~dev-python/aioecowitt-2025.9.2 )
	edimax? ( ~dev-python/pyedimax-0.2.1 )
	edl21? ( ~dev-python/pysml-0.1.5 )
	efergy? ( ~dev-python/pyefergy-22.5.0 )
	egardia? ( ~dev-python/pythonegardia-1.0.52 )
	egauge? ( ~dev-python/egauge-async-0.4.0 )
	eheimdigital? ( ~dev-python/eheimdigital-1.6.0 )
	ekeybionyx? ( ~dev-python/ekey-bionyxpy-1.0.1 )
	electrasmart? ( ~dev-python/pyelectra-1.2.4 )
	electric-kiwi? ( ~dev-python/electrickiwi-api-0.9.14 )
	elevenlabs? ( ~dev-python/elevenlabs-2.3.0 ~dev-python/sentence-stream-1.2.0 )
	elgato? ( ~dev-python/elgato-5.1.2 )
	eliqonline? ( ~dev-python/eliqonline-1.2.2 )
	elkm1? ( ~dev-python/elkm1-lib-2.2.13 )
	elmax? ( ~dev-python/elmax-api-0.0.6.4_rc0 )
	elvia? ( ~dev-python/elvia-0.1.0 )
	elv? ( ~dev-python/pypca-0.0.7 )
	emby? ( ~dev-python/pyemby-1.10 )
	emoncms-history? ( ~dev-python/pyemoncms-0.1.3 )
	emoncms? ( ~dev-python/pyemoncms-0.1.3 )
	emonitor? ( ~dev-python/aioemonitor-1.0.5 )
	emulated-kasa? ( ~dev-python/sense-energy-0.13.8 )
	emulated-roku? ( ~dev-python/emulated-roku-0.3.0 )
	energenie-power-sockets? ( ~dev-python/pyegps-0.2.5 )
	energyid? ( ~dev-python/energyid-webhooks-0.0.14 )
	energyzero? ( ~dev-python/energyzero-4.0.1 )
	enigma2? ( ~dev-python/openwebifpy-4.3.1 )
	enocean? ( ~dev-python/enocean-0.50.1 )
	enphase-envoy? ( ~dev-python/pyenphase-2.4.5 )
	entur-public-transport? ( ~dev-python/enturclient-0.2.4 )
	environment-canada? ( ~dev-python/env-canada-0.12.4 )
	envisalink? ( ~dev-python/pyenvisalink-4.7 )
	ephember? ( ~dev-python/pyephember2-0.4.12 )
	epic-games-store? ( ~dev-python/epicstore-api-0.1.7 )
	epion? ( ~dev-python/epion-0.0.3 )
	epson? ( ~dev-python/epson-projector-0.6.0 )
	eq3btsmart? ( ~dev-python/eq3btsmart-2.3.0 )
	escea? ( ~dev-python/pescea-1.0.12 )
	esphome? ( ~dev-python/aioesphomeapi-44.1.0 ~dev-python/bleak-esphome-3.6.0 ~dev-python/esphome-dashboard-api-1.3.0 )
	essent? ( ~dev-python/essent-dynamic-pricing-0.3.1 )
	etherscan? ( ~dev-python/python-etherscan-api-0.0.3 )
	eufylife-ble? ( ~dev-python/eufylife-ble-client-0.1.8 )
	eufy? ( ~dev-python/lakeside-0.13 )
	everlights? ( ~dev-python/pyeverlights-0.1.0 )
	evil-genius-labs? ( ~dev-python/pyevilgenius-2.0.0 )
	evohome? ( ~dev-python/evohome-async-1.1.3 )
	ezviz? ( ~dev-python/pyezvizapi-1.0.0.7 )
	faa-delays? ( ~dev-python/faadelays-2023.9.1 )
	familyhub? ( ~dev-python/python-family-hub-local-0.0.2 )
	fastdotcom? ( ~dev-python/fastdotcom-0.0.6 )
	feedreader? ( ~dev-python/feedparser-6.0.12 )
	ffmpeg? ( ~dev-python/ha-ffmpeg-3.2.2 )
	fibaro? ( ~dev-python/pyfibaro-0.8.3 )
	fido? ( ~dev-python/pyfido-2.1.2 )
	file? ( ~dev-python/file-read-backwards-2.0.0 )
	fing? ( ~dev-python/fing-agent-api-1.0.3 )
	fints? ( ~dev-python/fints-3.1.0 )
	firefly-iii? ( ~dev-python/pyfirefly-0.1.12 )
	fireservicerota? ( ~dev-python/pyfireservicerota-0.0.46 )
	firmata? ( ~dev-python/pymata-express-1.19 )
	fish-audio? ( ~dev-python/fish-audio-sdk-1.1.0 )
	fitbit? ( ~dev-python/fitbit-web-api-2.13.5 ~dev-python/fitbit-0.3.1 )
	fivem? ( ~dev-python/fivem-api-0.1.2 )
	fixer? ( ~dev-python/fixerio-1.0.0_alpha0 )
	fjaraskupan? ( ~dev-python/fjaraskupan-2.3.3 )
	fleetgo? ( ~dev-python/ritassist-0.9.2 )
	flexit-bacnet? ( ~dev-python/flexit-bacnet-2.2.3 )
	flic? ( ~dev-python/pyflic-2.0.4 )
	flipr? ( ~dev-python/flipr-api-1.6.1 )
	flo? ( ~dev-python/aioflo-2021.11.0 )
	flume? ( ~dev-python/pyflume-0.6.5 )
	fluss? ( ~dev-python/fluss-api-0.1.9.20 )
	flux-led? ( ~dev-python/flux-led-1.2.0 )
	folder-watcher? ( ~dev-python/watchdog-6.0.0 )
	foobot? ( ~dev-python/foobot-async-1.0.0 )
	forecast-solar? ( ~dev-python/forecast-solar-5.0.0 )
	forked-daapd? ( ~dev-python/pyforked-daapd-0.1.14 ~dev-python/pylibrespot-java-0.1.1 )
	fortios? ( ~dev-python/fortiosapi-1.0.5 )
	foscam? ( ~dev-python/libpyfoscamcgi-0.0.9 )
	freebox? ( ~dev-python/freebox-api-1.3.0 )
	freedompro? ( ~dev-python/pyfreedompro-1.1.0 )
	free-mobile? ( ~dev-python/freesms-0.2.0 )
	fressnapf-tracker? ( ~dev-python/fressnapftracker-0.2.2 )
	fritzbox-callmonitor? ( ~dev-python/fritzconnection-1.15.1[qrcode] )
	fritzbox? ( ~dev-python/pyfritzhome-0.6.20 )
	fritz? ( ~dev-python/fritzconnection-1.15.1[qrcode] ~dev-python/xmltodict-1.0.2 )
	fronius? ( ~dev-python/pyfronius-0.8.0 )
	frontend? ( ~dev-python/home-assistant-frontend-20260312.0 )
	frontier-silicon? ( ~dev-python/afsapi-0.2.7 )
	fujitsu-fglair? ( ~dev-python/ayla-iot-unofficial-1.4.7 )
	fully-kiosk? ( ~dev-python/python-fullykiosk-0.0.14 )
	futurenow? ( ~dev-python/pyfnip-0.2 )
	fyta? ( ~dev-python/fyta-cli-0.7.2 )
	garages-amsterdam? ( ~dev-python/odp-amsterdam-6.1.2 )
	gardena-bluetooth? ( ~dev-python/gardena-bluetooth-1.6.0 )
	gc100? ( ~dev-python/python-gc100-1.0.3_alpha0 )
	gdacs? ( ~dev-python/aio-georss-gdacs-0.10 )
	generic? ( ~dev-python/pillow-12.1.1 ~dev-python/av-16.0.1 )
	geniushub? ( ~dev-python/geniushub-client-0.7.1 )
	gentex-homelink? ( ~dev-python/homelink-integration-api-0.0.1 )
	geocaching? ( ~dev-python/geocachingapi-0.3.0 )
	geo-json-events? ( ~dev-python/aio-geojson-generic-client-0.5 )
	geonetnz-quakes? ( ~dev-python/aio-geojson-geonetnz-quakes-0.16 )
	geonetnz-volcano? ( ~dev-python/aio-geojson-geonetnz-volcano-0.9 )
	geo-rss-events? ( ~dev-python/georss-generic-client-0.8 )
	ghost? ( ~dev-python/aioghost-0.4.0 )
	gios? ( ~dev-python/gios-7.0.0 )
	github? ( ~dev-python/aiogithubapi-26.0.0 )
	gitlab-ci? ( ~dev-vcs/python-gitlab-1.6.0 )
	gitter? ( ~dev-python/gitterpy-0.1.7 )
	glances? ( ~dev-python/glances-api-0.8.0 )
	go2rtc? ( ~dev-python/go2rtc-client-0.4.0 )
	goalzero? ( ~dev-python/goalzero-0.2.2 )
	gogogate2? ( ~dev-python/ismartgate-5.0.2 )
	goodwe? ( ~dev-python/goodwe-0.4.8 )
	google-air-quality? ( ~dev-python/google-air-quality-api-3.0.1 )
	google-assistant-sdk? ( ~dev-python/gassist-text-0.0.14 )
	google-cloud? ( ~dev-python/google-cloud-speech-2.31.1 ~dev-python/google-cloud-texttospeech-2.25.1 )
	google-drive? ( ~dev-python/python-google-drive-api-0.1.0 )
	google-generative-ai-conversation? ( ~dev-python/google-genai-1.59.0 )
	google-mail? ( ~dev-python/google-api-python-client-2.71.0 )
	google? ( ~dev-python/gcal-sync-8.0.0 ~dev-python/ical-13.2.2 ~dev-python/oauth2client-4.1.3 )
	google-maps? ( ~dev-python/locationsharinglib-5.0.1 )
	google-photos? ( ~dev-python/google-photos-library-api-0.12.1 )
	google-pubsub? ( ~dev-python/google-cloud-pubsub-2.29.0 )
	google-sheets? ( ~dev-python/gspread-5.5.0 )
	google-tasks? ( ~dev-python/google-api-python-client-2.71.0 )
	google-translate? ( ~dev-python/gtts-2.5.3 )
	google-travel-time? ( ~dev-python/google-maps-routing-0.6.15 )
	google-weather? ( ~dev-python/python-google-weather-api-0.0.4 )
	govee-ble? ( ~dev-python/govee-ble-0.44.0 )
	govee-light-local? ( ~dev-python/govee-local-api-2.4.0 )
	gpsd? ( ~dev-python/gps3-0.33.3 )
	gree? ( ~dev-python/greeclimate-2.1.1 )
	greeneye-monitor? ( ~dev-python/greeneye-monitor-3.0.3 )
	green-planet-energy? ( ~dev-python/greenplanet-energy-api-0.1.4 )
	greenwave? ( ~dev-python/greenwavereality-0.5.1 )
	growatt-server? ( ~dev-python/growattserver-1.9.0 )
	gtfs? ( ~dev-python/pygtfs-0.1.9 )
	guardian? ( ~dev-python/aioguardian-2026.1.1 )
	habitica? ( ~dev-python/habiticalib-0.4.6 )
	hanna? ( ~dev-python/hanna-cloud-0.0.7 )
	hardware? ( ~dev-python/psutil-home-assistant-0.0.1 )
	harman-kardon-avr? ( ~dev-python/hkavr-0.0.5 )
	harmony? ( ~dev-python/aioharmony-0.5.3 )
	hassio? ( ~dev-python/aiohasupervisor-0.3.3 )
	hdfury? ( ~dev-python/hdfury-1.6.0 )
	hdmi-cec? ( ~dev-python/pycec-0.5.2 )
	heatmiser? ( ~dev-python/heatmiserv3-2.0.4 )
	hegel? ( ~dev-python/hegel-ip-client-0.1.4 )
	heos? ( ~dev-python/pyheos-1.0.6 )
	here-travel-time? ( ~dev-python/here-routing-1.2.0 ~dev-python/here-transit-1.2.1 )
	hikvisioncam? ( ~dev-python/hikvision-0.4 )
	hikvision? ( ~dev-python/pyhik-0.4.2 )
	hisense-aehw4a1? ( ~dev-python/pyaehw4a1-0.3.9 )
	hive? ( ~dev-python/pyhive-integration-1.0.8 )
	hko? ( ~dev-python/hko-0.3.2 )
	hlk-sw16? ( ~dev-python/hlk-sw16-0.0.9 )
	holiday? ( ~dev-python/babel-2.15.0 ~dev-python/holidays-0.84 )
	homeassistant-hardware? ( ~dev-python/ha-silabs-firmware-client-0.3.0 ~dev-python/serialx-0.6.2 ~dev-python/universal-silabs-flasher-0.1.2 )
	home-connect? ( ~dev-python/aiohomeconnect-0.28.0 )
	homee? ( ~dev-python/pyhomee-1.3.8 )
	homekit-controller? ( ~dev-python/aiohomekit-3.2.20 )
	homekit? ( ~dev-python/hap-python-5.0.0 ~dev-python/pyqrcode-1.2.1 ~dev-python/base36-0.1.1 ~dev-python/fnv-hash-fast-1.6.0 )
	homematicip-cloud? ( ~dev-python/homematicip-2.6.0 )
	homematic? ( ~dev-python/pyhomematic-0.1.77 )
	homevolt? ( ~dev-python/homevolt-0.5.0 )
	homewizard? ( ~dev-python/python-homewizard-energy-10.0.1 )
	homeworks? ( ~dev-python/pyhomeworks-1.1.2 )
	honeywell? ( ~dev-python/aiosomecomfort-0.0.35 )
	horizon? ( ~dev-python/horimote-0.4.1 )
	hp-ilo? ( ~dev-python/python-hpilo-4.4.3 )
	html5? ( ~dev-python/py-vapid-1.9.4 ~dev-python/pywebpush-2.3.0 )
	huawei-lte? ( ~dev-python/huawei-lte-api-1.11.0 ~dev-python/url-normalize-2.2.1 )
	hue-ble? ( ~dev-python/hueble-2.1.0 )
	hue? ( ~dev-python/aiohue-4.8.0 )
	huisbaasje? ( ~dev-python/energyflip-client-0.2.2 )
	hunterdouglas-powerview? ( ~dev-python/aiopvapi-3.3.0 )
	husqvarna-automower-ble? ( ~dev-python/automower-ble-0.2.8 ~dev-python/gardena-bluetooth-1.6.0 )
	husqvarna-automower? ( ~dev-python/aioautomower-2.7.3 )
	huum? ( ~dev-python/huum-0.8.1 )
	hvv-departures? ( ~dev-python/pygti-0.9.4 )
	hydrawise? ( ~dev-python/pydrawise-2025.9.0 )
	hyperion? ( ~dev-python/hyperion-py-0.7.6 )
	hypontech? ( ~dev-python/hyponcloud-0.3.0 )
	ialarm? ( ~dev-python/pyialarm-2.2.0 )
	iammeter? ( ~dev-python/iammeter-0.2.1 )
	iaqualink? ( ~dev-python/h2-4.3.0 ~dev-python/iaqualink-0.6.0 )
	ibeacon? ( ~dev-python/ibeacon-ble-1.2.0 )
	icloud? ( ~dev-python/pyicloud-2.4.1 )
	idasen-desk? ( ~dev-python/idasen-ha-2.6.4 )
	idrive-e2? ( ~dev-python/aiobotocore-2.21.1 ~dev-python/idrive-e2-client-0.1.1 )
	idteck-prox? ( ~dev-python/rfk101py-0.0.1 )
	ifttt? ( >=dev-python/pyfttt-0.3.0 )
	iglo? ( ~dev-python/iglo-1.2.7 )
	igloohome? ( ~dev-python/igloohome-api-0.1.1 )
	ign-sismologia? ( ~dev-python/georss-ign-sismologia-client-0.8 )
	ihc? ( =dev-python/defusedxml-0.7.1-r1 ~dev-python/ihcsdk-2.8.5 )
	image-upload? ( ~dev-python/pillow-12.1.1 )
	imap? ( ~dev-python/aioimaplib-2.0.1 )
	imeon-inverter? ( ~dev-python/imeon-inverter-api-0.4.0 )
	imgw-pib? ( ~dev-python/imgw-pib-2.0.2 )
	immich? ( ~dev-python/aioimmich-0.12.0 )
	improv-ble? ( ~dev-python/py-improv-ble-client-2.0.1 )
	incomfort? ( ~dev-python/incomfort-client-0.6.12 )
	indevolt? ( ~dev-python/indevolt-api-1.2.3 )
	inels? ( ~dev-python/elkoep-aio-mqtt-0.1.0_beta4 )
	influxdb? ( ~dev-python/influxdb-client-1.50.0 ~dev-python/influxdb-5.3.1 )
	inkbird? ( ~dev-python/inkbird-ble-1.1.1 )
	insteon? ( ~dev-python/insteon-frontend-home-assistant-0.6.1 ~dev-python/pyinsteon-1.6.4 )
	intelliclima? ( ~dev-python/pyintelliclima-0.2.2 )
	intellifire? ( ~dev-python/intellifire4py-4.3.1 )
	intesishome? ( ~dev-python/pyintesishome-1.8.0 )
	iometer? ( ~dev-python/iometer-0.4.0 )
	iotawatt? ( ~dev-python/ha-iotawattpy-0.1.2 )
	iotty? ( ~dev-python/iottycloud-0.3.0 )
	iperf3? ( ~dev-python/iperf3-0.1.11 )
	ipma? ( ~dev-python/pyipma-3.0.9 )
	ipp? ( ~dev-python/pyipp-0.17.0 )
	iqvia? ( ~dev-python/numpy-2.3.2 ~dev-python/pyiqvia-2022.4.0 )
	irish-rail-transport? ( ~dev-python/pyirishrail-0.0.2 )
	irm-kmi? ( ~dev-python/irm-kmi-api-1.1.1 )
	iron-os? ( ~dev-python/pynecil-4.2.1 )
	isal? ( ~dev-python/isal-1.8.0 )
	iskra? ( ~dev-python/pyiskra-0.1.27 )
	islamic-prayer-times? ( ~dev-python/prayer-times-calculator-offline-1.0.3 )
	israel-rail? ( ~dev-python/israel-rail-api-0.1.4 )
	iss? ( ~dev-python/pyiss-1.0.1 )
	ista-ecotrend? ( ~dev-python/pyecotrend-ista-3.4.0 )
	isy994? ( ~dev-python/pyisy-3.4.1 )
	itach? ( ~dev-python/pyitachip2ir-0.0.7 )
	ituran? ( ~dev-python/pyituran-0.1.5 )
	izone? ( ~dev-python/python-izone-1.2.9 )
	jellyfin? ( ~dev-python/jellyfin-apiclient-python-1.11.0 )
	jewish-calendar? ( ~dev-python/hdate-1.1.2[astral] )
	joaoapps-join? ( ~dev-python/python-join-api-0.0.9 )
	justnimbus? ( ~dev-python/justnimbus-0.7.4 )
	jvc-projector? ( ~dev-python/pyjvcprojector-2.0.3 )
	kaiterra? ( ~dev-python/kaiterra-async-client-1.0.0 )
	kaleidescape? ( ~dev-python/pykaleidescape-1.1.3 )
	keba? ( ~dev-python/keba-kecontact-1.3.0 )
	keenetic-ndms2? ( ~dev-python/ndms2-client-0.1.2 )
	kef? ( ~dev-python/aiokef-0.2.16 ~dev-python/getmac-0.9.5 )
	kegtron? ( ~dev-python/kegtron-ble-1.0.2 )
	keyboard-remote? ( ~dev-python/asyncinotify-4.4.0 ~dev-python/evohome-async-1.1.3 )
	keymitt-ble? ( ~dev-python/pymicrobot-0.0.23 )
	kira? ( ~dev-python/pykira-0.1.1 )
	kiwi? ( ~dev-python/kiwiki-client-0.1.1 )
	kmtronic? ( ~dev-python/pykmtronic-0.3.0 )
	knocki? ( ~dev-python/knocki-0.4.2 )
	knx? ( ~dev-python/knx-frontend-2026.3.2.183756 ~dev-python/xknx-3.15.0 ~dev-python/xknxproject-3.8.2 )
	kodi? ( ~dev-python/pykodi-0.2.7 )
	konnected? ( ~dev-python/konnected-1.2.0 )
	kostal-plenticore? ( ~dev-python/pykoplenti-1.5.0 )
	kraken? ( ~dev-python/krakenex-2.2.2 ~dev-python/pykrakenapi-0.1.8 )
	kulersky? ( ~dev-python/pykulersky-0.5.8 )
	kwb? ( ~dev-python/pykwb-0.0.8 )
	lacrosse? ( ~dev-python/pylacrosse-0.4 )
	lacrosse-view? ( ~dev-python/lacrosse-view-1.1.1 )
	lamarzocco? ( ~dev-python/pylamarzocco-2.2.4 )
	lametric? ( ~dev-python/demetriek-1.3.0 )
	landisgyr-heat-meter? ( ~dev-python/ultraheat-api-0.5.7 )
	lastfm? ( ~dev-python/pylast-5.1.0 )
	launch-library? ( ~dev-python/pylaunches-2.0.0 )
	laundrify? ( ~dev-python/laundrify-aio-1.2.2 )
	lcn? ( ~dev-python/lcn-frontend-0.2.7 ~dev-python/pypck-0.9.11 )
	ld2410-ble? ( ~dev-python/bluetooth-data-tools-1.28.4 ~dev-python/ld2410-ble-0.1.1 )
	leaone? ( ~dev-python/leaone-ble-0.3.0 )
	led-ble? ( ~dev-python/bluetooth-data-tools-1.28.4 ~dev-python/led-ble-1.1.7 )
	lektrico? ( ~dev-python/lektricowifi-0.1 )
	letpot? ( ~dev-python/letpot-0.6.4 )
	lg-netcast? ( ~dev-python/pylgnetcast-0.3.9 )
	lg-soundbar? ( ~dev-python/temescal-0.5 )
	lg-thinq? ( ~dev-python/thinqconnect-1.0.9 )
	libre-hardware-monitor? ( ~dev-python/librehardwaremonitor-api-1.10.1 )
	lidarr? ( ~dev-python/aiopyarr-23.4.0 )
	liebherr? ( ~dev-python/pyliebherrhomeapi-0.3.0 )
	lifx? ( ~dev-python/aiolifx-effects-0.3.2 ~dev-python/aiolifx-themes-1.0.2 ~dev-python/aiolifx-1.2.1 )
	lightwave? ( ~dev-python/lightwave-0.24 )
	limitlessled? ( ~dev-python/limitlessled-1.1.3 )
	linkplay? ( ~dev-python/python-linkplay-0.2.12 )
	linode? ( ~dev-python/linode-api-4.1.9_beta1 )
	linux-battery? ( ~dev-python/batinfo-0.4.2 )
	litejet? ( ~dev-python/pylitejet-0.6.3 )
	litterrobot? ( ~dev-python/pylitterbot-2025.1.0 )
	livisi? ( ~dev-python/livisi-0.0.25 )
	local-calendar? ( ~dev-python/ical-13.2.2 )
	local-todo? ( ~dev-python/ical-13.2.2 )
	london-underground? ( ~dev-python/london-tube-status-0.5 )
	lookin? ( ~dev-python/aiolookin-1.0.0 )
	loqed? ( ~dev-python/loqedapi-2.1.10 )
	luci? ( ~dev-python/openwrt-luci-rpc-1.1.17 )
	luftdaten? ( ~dev-python/luftdaten-0.7.4 )
	lunatone? ( ~dev-python/lunatone-rest-api-client-0.7.0 )
	lupusec? ( ~dev-python/lupupy-0.3.2 )
	lutron-caseta? ( ~dev-python/pylutron-caseta-0.26.0 )
	lutron? ( ~dev-python/pylutron-0.2.18 )
	lw12wifi? ( ~dev-python/lw12-0.9.2 )
	lyric? ( ~dev-python/aiolyric-2.0.2 )
	madvr? ( ~dev-python/py-madvr2-1.6.40 )
	mailgun? ( ~dev-python/pymailgunner-1.4 )
	marytts? ( ~dev-python/speak2mary-1.4.0 )
	mastodon? ( ~dev-python/mastodon-py-2.1.2 )
	matrix? ( ~dev-python/pillow-12.1.1 ~dev-python/aiofiles-24.1.0 ~dev-python/matrix-nio-0.25.2 )
	matter? ( ~dev-python/matter-python-client-0.4.1 )
	maxcube? ( ~dev-python/maxcube-api-0.4.3 )
	mcp? ( ~dev-python/mcp-1.26.0 )
	mcp-server? ( ~dev-python/aiohttp-sse-2.2.0 ~dev-python/anyio-4.10.0 ~dev-python/mcp-1.26.0 )
	mealie? ( ~dev-python/aiomealie-1.2.1 )
	meater? ( ~dev-python/meater-python-0.0.8 )
	medcom-ble? ( ~dev-python/medcom-ble-0.1.1 )
	media-extractor? ( ~net-misc/yt-dlp-2026.02.21[default] )
	mediaroom? ( ~dev-python/pymediaroom-0.6.5.4 )
	melcloud? ( ~dev-python/python-melcloud-0.1.2 )
	melissa? ( ~dev-python/py-melissa-climate-3.0.3 )
	melnor? ( ~dev-python/melnor-bluetooth-0.0.25 )
	message-bird? ( ~dev-python/messagebird-1.2.0 )
	met-eireann? ( ~dev-python/pymeteireann-2024.11.0 )
	meteoalarm? ( ~dev-python/meteoalertapi-0.3.1 )
	meteoclimatic? ( ~dev-python/pymeteoclimatic-0.1.1 )
	meteo-france? ( ~dev-python/meteofrance-api-1.5.0 )
	meteo-lt? ( ~dev-python/meteo-lt-pkg-0.2.4 )
	met? ( ~dev-python/pymetno-0.13.0 )
	metoffice? ( ~dev-python/datapoint-0.12.1 )
	mfi? ( ~dev-python/mficlient-0.5.0 )
	microbees? ( ~dev-python/microbeespy-0.3.5 )
	microsoft? ( ~dev-python/pycsspeechtts-1.0.8 )
	miele? ( ~dev-python/pymiele-0.6.1 )
	mikrotik? ( ~dev-python/librouteros-3.2.0 )
	mill? ( ~dev-python/mill-local-0.5.0 ~dev-python/millheater-0.14.1 )
	minecraft-server? ( ~dev-python/mcstatus-12.1.0 )
	minio? ( ~dev-python/minio-7.1.12 )
	moat? ( ~dev-python/moat-ble-0.1.1 )
	mobile-app? ( ~dev-python/pynacl-1.6.2 )
	mochad? ( ~dev-python/pymochad-0.2.0 )
	modbus? ( ~dev-python/pymodbus-3.11.2 )
	modem-callerid? ( ~dev-python/phone-modem-0.1.1 )
	modern-forms? ( ~dev-python/aiomodernforms-0.1.8 )
	moehlenhoff-alpha2? ( ~dev-python/moehlenhoff-alpha2-1.4.0 )
	monarch-money? ( ~dev-python/typedmonarchmoney-0.7.0 )
	monoprice? ( ~dev-python/pymonoprice-0.5 )
	monzo? ( ~dev-python/monzopy-1.5.1 )
	mopeka? ( ~dev-python/mopeka-iot-ble-0.8.0 )
	motionblinds-ble? ( ~dev-python/motionblindsble-0.1.3 )
	motion-blinds? ( ~dev-python/motionblinds-0.6.30 )
	motioneye? ( ~dev-python/motioneye-client-0.3.14 )
	motionmount? ( ~dev-python/python-motionmount-2.3.0 )
	mpd? ( ~dev-python/python-mpd2-3.1.1 )
	mqtt? ( ~dev-python/paho-mqtt-2.1.0 )
	msteams? ( ~dev-python/pymsteams-0.1.12 )
	mta? ( ~dev-python/py-nymta-0.4.0 )
	mullvad? ( ~dev-python/mullvad-api-1.0.0 )
	music-assistant? ( ~dev-python/music-assistant-client-1.3.3 )
	mutesync? ( ~dev-python/mutesync-0.0.1 )
	mvglive? ( ~dev-python/mvg-1.4.0 )
	myneomitis? ( ~dev-python/pyaxencoapi-1.0.6 )
	mysensors? ( ~dev-python/pymysensors-0.26.0 )
	mystrom? ( ~dev-python/python-mystrom-2.5.0 )
	mythicbeastsdns? ( ~dev-python/mbddns-0.1.2 )
	myuplink? ( ~dev-python/myuplink-0.7.0 )
	nad? ( ~dev-python/nad-receiver-0.3.0 )
	nam? ( ~dev-python/nettigo-air-monitor-5.0.0 )
	nanoleaf? ( ~dev-python/aionanoleaf2-1.0.2 )
	nasweb? ( ~dev-python/webio-api-0.1.12 )
	neato? ( ~dev-python/pybotvac-0.0.28 )
	nederlandse-spoorwegen? ( ~dev-python/nsapi-3.1.3 )
	ness-alarm? ( ~dev-python/nessclient-1.3.1 )
	nest? ( ~dev-python/google-nest-sdm-9.1.2 )
	netatmo? ( ~dev-python/pyatmo-9.2.3 )
	netdata? ( ~dev-python/netdata-1.3.0 )
	netgear-lte? ( ~dev-python/eternalegypt-0.0.18 )
	netgear? ( ~dev-python/pynetgear-0.10.10 )
	netio? ( ~dev-python/pynetio-0.1.9.1 )
	network? ( ~dev-python/ifaddr-0.2.0 )
	neurio-energy? ( ~dev-python/neurio-0.3.1 )
	nexia? ( ~dev-python/nexia-2.11.1 )
	nextbus? ( ~dev-python/py-nextbusnext-2.3.0 )
	nextcloud? ( ~dev-python/nextcloudmonitor-1.5.1 )
	nextdns? ( ~dev-python/nextdns-5.0.0 )
	nfandroidtv? ( ~dev-python/notifications-android-tv-0.1.5 )
	nibe-heatpump? ( ~dev-python/nibe-2.22.0 )
	nice-go? ( ~dev-python/nice-go-1.0.1 )
	nightscout? ( ~dev-python/py-nightscout-1.2.2 )
	niko-home-control? ( ~dev-python/nhc-0.7.0 )
	nilu? ( ~dev-python/niluclient-0.1.2 )
	nina? ( ~dev-python/pynina-1.0.2 )
	nintendo-parental-controls? ( ~dev-python/pynintendoauth-1.0.2 ~dev-python/pynintendoparental-2.3.2.1 )
	nissan-leaf? ( ~dev-python/pycarwings2-2.14 )
	nmap-tracker? ( ~dev-python/aiooui-0.1.9 ~dev-python/getmac-0.9.5 ~dev-python/netmap-0.7.0.2 )
	nmbs? ( ~dev-python/pyrail-0.4.1 )
	noaa-tides? ( ~dev-python/noaa-coops-0.4.0 )
	nobo-hub? ( ~dev-python/pynobo-1.8.1 )
	nordpool? ( ~dev-python/pynordpool-0.3.2 )
	norway-air? ( ~dev-python/pymetno-0.13.0 )
	notify-events? ( ~dev-python/notify-events-1.0.4 )
	notion? ( ~dev-python/aionotion-2024.3.0 )
	nrgkick? ( ~dev-python/nrgkick-api-1.7.1 )
	nsw-fuel-station? ( ~dev-python/nsw-fuel-api-client-1.1.0 )
	nsw-rural-fire-service-feed? ( ~dev-python/aio-geojson-nsw-rfs-incidents-0.7 )
	ntfy? ( ~dev-python/aiontfy-0.8.1 )
	nuheat? ( ~dev-python/nuheat-1.0.1 )
	nuki? ( ~dev-python/pynuki-1.6.3 )
	numato? ( ~dev-python/numato-gpio-0.13.0 )
	nut? ( ~dev-python/aionut-4.3.4 )
	nws? ( ~dev-python/pynws-1.8.2[retry] )
	nx584? ( ~dev-python/pynx584-0.8.2 )
	nyt-games? ( ~dev-python/nyt-games-0.5.0 )
	nzbget? ( ~dev-python/pynzbgetapi-0.2.0 )
	oasa-telematics? ( ~dev-python/oasatelematics-0.3 )
	obihai? ( ~dev-python/pyobihai-1.4.2 )
	octoprint? ( ~dev-python/pyoctoprintapi-0.1.14 )
	oem? ( ~dev-python/oemthermostat-1.1.1 )
	ohmconnect? ( =dev-python/defusedxml-0.7.1-r1 )
	ohme? ( ~dev-python/ohme-1.7.0 )
	ollama? ( ~dev-python/ollama-0.5.1 )
	ombi? ( ~dev-python/pyombi-0.1.10 )
	omnilogic? ( ~dev-python/omnilogic-0.4.5 )
	ondilo-ico? ( ~dev-python/ondilo-0.5.0 )
	onedrive-for-business? ( ~dev-python/onedrive-personal-sdk-0.1.7 )
	onedrive? ( ~dev-python/onedrive-personal-sdk-0.1.7 )
	onewire? ( ~dev-python/aio-ownet-0.0.5 )
	onkyo? ( ~dev-python/aioonkyo-0.4.0 )
	onvif? ( ~dev-python/wsdiscovery-2.1.2 ~dev-python/onvif-zeep-async-4.0.4 )
	openai-conversation? ( ~dev-python/openai-2.21.0 )
	openerz? ( ~dev-python/openerz-api-0.3.0 )
	openevse? ( ~dev-python/python-openevse-http-0.2.1 )
	openexchangerates? ( ~dev-python/aioopenexchangerates-0.6.8 )
	opengarage? ( ~dev-python/open-garage-0.2.0 )
	openhome? ( ~dev-python/openhomedevice-2.2 )
	open-meteo? ( ~dev-python/open-meteo-0.3.2 )
	openrgb? ( ~dev-python/openrgb-python-0.3.6 )
	open-router? ( ~dev-python/openai-2.21.0 ~dev-python/python-open-router-0.3.3 )
	opensensemap? ( ~dev-python/opensensemap-api-0.2.0 )
	opensky? ( ~dev-python/python-opensky-1.0.1 )
	opentherm-gw? ( ~dev-python/pyotgw-2.2.3 )
	openuv? ( ~dev-python/pyopenuv-2023.2.0 )
	openweathermap? ( ~dev-python/pyopenweathermap-0.2.2 )
	opnsense? ( ~dev-python/pyopnsense-0.4.0 )
	opower? ( ~dev-python/opower-0.17.0 )
	opple? ( ~dev-python/pyoppleio-legacy-1.0.8 )
	oralb? ( ~dev-python/oralb-ble-1.0.2 )
	oru? ( ~dev-python/oru-0.1.11 )
	orvibo? ( ~dev-python/orvibo-1.1.2 )
	osoenergy? ( ~dev-python/pyosoenergyapi-1.2.4 )
	osramlightify? ( ~dev-python/lightify-1.0.7.3 )
	otbr? ( ~dev-python/python-otbr-api-2.9.0 )
	otp? ( ~dev-python/pyotp-2.9.0 )
	ourgroceries? ( ~dev-python/ourgroceries-1.5.4 )
	overkiz? ( ~dev-python/pyoverkiz-1.20.0 )
	overseerr? ( ~dev-python/python-overseerr-0.9.0 )
	ovo-energy? ( ~dev-python/ovoenergy-3.0.2 )
	owntracks? ( ~dev-python/pynacl-1.6.2 )
	p1-monitor? ( ~dev-python/p1monitor-3.2.0 )
	palazzetti? ( ~dev-python/pypalazzetti-0.1.20 )
	panasonic-bluray? ( ~dev-python/panacotta-0.2 )
	panasonic-viera? ( ~dev-python/panasonic-viera-0.4.4 )
	paperless-ngx? ( ~dev-python/pypaperless-4.1.1 )
	peblar? ( ~dev-python/peblar-0.4.0 )
	peco? ( ~dev-python/peco-0.1.2 )
	pegel-online? ( ~dev-python/aiopegelonline-0.1.1 )
	pencom? ( ~dev-python/pencompy-0.0.3 )
	permobil? ( ~dev-python/mypermobil-0.1.8 )
	pglab? ( ~dev-python/pypglab-0.0.5 )
	philips-js? ( ~dev-python/ha-philipsjs-3.2.4 )
	picnic? ( ~dev-python/python-picnic-api-1.3.1 )
	pi-hole? ( ~dev-python/hole-0.9.0 )
	pilight? ( ~dev-python/pilight-0.1.1 )
	ping? ( >=dev-python/icmplib-3.0.0 )
	pjlink? ( ~dev-python/pypjlink2-1.2.1 )
	plaato? ( ~dev-python/pyplaato-0.0.19 )
	playstation-network? ( ~dev-python/psnawp-3.0.1 ~dev-python/pyrate-limiter-3.9.0 )
	plex? ( ~dev-python/plexapi-4.15.16 ~dev-python/plexauth-0.0.6 ~dev-python/plexwebsocket-0.0.14 )
	plugwise? ( ~dev-python/plugwise-1.11.2 )
	pocketcasts? ( ~dev-python/pycketcasts-1.0.1 )
	point? ( ~dev-python/pypoint-3.0.0 )
	pooldose? ( ~dev-python/python-pooldose-0.8.2 )
	poolsense? ( ~dev-python/poolsense-0.0.8 )
	portainer? ( ~dev-python/pyportainer-1.0.33 )
	powerfox-local? ( ~dev-python/powerfox-2.1.1 )
	powerfox? ( ~dev-python/powerfox-2.1.1 )
	powerwall? ( ~dev-python/tesla-powerwall-0.5.2 )
	prana? ( ~dev-python/prana-api-client-0.10.0 )
	private-ble-device? ( ~dev-python/bluetooth-data-tools-1.28.4 )
	probe-plus? ( ~dev-python/pyprobeplus-1.1.2 )
	profiler? ( ~dev-python/guppy3-3.1.6 ~dev-python/objgraph-3.5.0 ~dev-python/pyprof2calltree-1.4.5 )
	progettihwsw? ( ~dev-python/progettihwsw-0.1.3 )
	proliphix? ( ~dev-python/proliphix-0.4.1 )
	prometheus? ( ~dev-python/prometheus-client-0.21.0 )
	prosegur? ( ~dev-python/pyprosegur-0.0.14 )
	prowl? ( ~dev-python/prowlpy-1.1.1 )
	proxmoxve? ( ~dev-python/proxmoxer-2.0.1 )
	proxy? ( ~dev-python/pillow-12.1.1 )
	prusalink? ( ~dev-python/pyprusalink-2.1.1 )
	ps4? ( ~dev-python/pyps4-2ndscreen-1.3.1 )
	pterodactyl? ( ~dev-python/py-dactyl-2.0.4 )
	pulseaudio-loopback? ( ~dev-python/pulsectl-23.5.2 )
	pure-energie? ( ~dev-python/gridnet-5.0.1 )
	purpleair? ( ~dev-python/aiopurpleair-2025.8.1 )
	pushbullet? ( ~dev-python/pushbullet-py-0.11.0 )
	pushover? ( ~dev-python/pushover-complete-1.2.0 )
	pvoutput? ( ~dev-python/pvo-2.2.1 )
	pvpc-hourly-pricing? ( ~dev-python/aiopvpc-4.2.2 )
	pyload? ( ~dev-python/pyloadapi-1.4.2 )
	python-script? ( ~dev-python/restrictedpython-8.1 )
	qbittorrent? ( ~dev-python/qbittorrent-api-2024.9.67 )
	qbus? ( ~dev-python/qbusmqttapi-1.4.2 )
	qingping? ( ~dev-python/qingping-ble-1.1.0 )
	qld-bushfire? ( ~dev-python/georss-qld-bushfire-alert-client-0.8 )
	qnap? ( ~dev-python/qnapstats-0.4.0 )
	qnap-qsw? ( ~dev-python/aioqsw-0.4.2 )
	qrcode? ( ~dev-python/pillow-12.1.1 ~dev-python/pyzbar-0.1.7 )
	quantum-gateway? ( ~dev-python/quantum-gateway-0.0.8 )
	qvr-pro? ( ~dev-python/pyqvrpro-0.52 )
	qwikswitch? ( ~dev-python/pyqwikswitch-0.93 )
	rabbitair? ( ~dev-python/python-rabbitair-0.0.8 )
	rachio? ( ~dev-python/rachiopy-1.1.0 )
	radarr? ( ~dev-python/aiopyarr-23.4.0 )
	radio-browser? ( ~dev-python/pycountry-24.6.1 ~dev-python/radios-0.3.2 )
	radiotherm? ( ~dev-python/radiotherm-2.1.0 )
	rainbird? ( ~dev-python/pyrainbird-6.1.0 )
	raincloud? ( ~dev-python/raincloudy-0.0.7 )
	rainforest-eagle? ( ~dev-python/aioeagle-1.1.0 ~dev-python/eagle100-0.1.1 )
	rainforest-raven? ( ~dev-python/aioraven-0.7.1 )
	rainmachine? ( ~dev-python/regenmaschine-2024.3.0 )
	rapt-ble? ( ~dev-python/rapt-ble-0.1.2 )
	raspyrfm? ( ~dev-python/raspyrfm-client-1.2.9 )
	rdw? ( ~dev-python/vehicle-2.2.2 )
	recollect-waste? ( ~dev-python/aiorecollect-2023.9.0 )
	recorder? ( ~dev-python/sqlalchemy-2.0.41 ~dev-python/fnv-hash-fast-1.6.0 ~dev-python/psutil-home-assistant-0.0.1 )
	recswitch? ( ~dev-python/pyrecswitch-1.0.2 )
	reddit? ( ~dev-python/praw-7.5.0 )
	redgtech? ( ~dev-python/redgtech-api-0.1.38 )
	refoss? ( ~dev-python/refoss-ha-1.2.5 )
	rehlko? ( ~dev-python/aiokem-1.0.1 )
	rejseplanen? ( ~dev-python/rjpl-0.3.6 )
	remember-the-milk? ( ~dev-python/rtmapi-0.7.2 ~dev-python/httplib2-0.20.4 )
	remote-calendar? ( ~dev-python/ical-13.2.2 )
	remote-rpi-gpio? ( ~dev-python/gpiozero-1.6.2 ~dev-python/pigpio-1.78 )
	renault? ( ~dev-python/renault-api-0.5.5 )
	renson? ( ~dev-python/renson-endura-delta-1.7.2 )
	reolink? ( ~dev-python/reolink-aio-0.19.1 )
	repetier? ( ~dev-python/pyrepetierng-0.1.0 )
	rest? ( ~dev-python/jsonpath-0.82.2 ~dev-python/xmltodict-1.0.2 )
	rflink? ( ~dev-python/rflink-0.0.67 )
	rfxtrx? ( ~dev-python/pyrfxtrx-0.31.1 )
	ridwell? ( ~dev-python/aioridwell-2025.9.0 )
	ring? ( ~dev-python/ring-doorbell-0.9.14 )
	ripple? ( ~dev-python/python-ripple-api-0.0.3 )
	risco? ( ~dev-python/pyrisco-0.6.7 )
	rituals-perfume-genie? ( ~dev-python/pyrituals-0.0.7 )
	rmvtransport? ( ~dev-python/pyrmvtransport-0.3.3 )
	roborock? ( ~dev-python/python-roborock-4.17.1 ~dev-python/vacuum-map-parser-roborock-0.1.4 )
	rocketchat? ( ~dev-python/rocketchat-api-0.6.1 )
	roku? ( ~dev-python/rokuecp-0.19.5 )
	romy? ( ~dev-python/romy-0.0.10 )
	roomba? ( ~dev-python/roombapy-1.9.0 )
	roon? ( ~dev-python/roonapi-0.1.6 )
	route53? ( ~dev-python/boto3-1.37.1 )
	route-b-smart-meter? ( ~dev-python/momonga-0.3.0 ~dev-python/pyserial-3.5 )
	rova? ( ~dev-python/rova-0.4.1 )
	rpi-power? ( ~dev-python/rpi-bad-power-0.1.0 )
	ruckus-unleashed? ( ~dev-python/aioruckus-0.42 )
	russound-rio? ( ~dev-python/aiorussound-4.9.0 )
	russound-rnet? ( ~dev-python/russound-0.1.9 )
	ruuvi-gateway? ( ~dev-python/aioruuvigateway-0.1.0 )
	ruuvitag-ble? ( ~dev-python/ruuvitag-ble-0.4.0 )
	rympro? ( ~dev-python/pyrympro-0.0.9 )
	sabnzbd? ( ~dev-python/pysabnzbd-1.1.1 )
	saj? ( ~dev-python/pysaj-0.0.16 )
	samsungtv? ( ~dev-python/async-upnp-client-0.46.2 ~dev-python/getmac-0.9.5 ~dev-python/samsungctl-0.7.1[websocket] ~dev-python/samsungtvws-2.7.2[async,encrypted] ~dev-python/wakeonlan-3.1.0 )
	sanix? ( ~dev-python/sanix-1.0.6 )
	satel-integra? ( ~dev-python/satel-integra-0.3.7 )
	saunum? ( ~dev-python/pysaunum-0.5.0 )
	schlage? ( ~dev-python/pyschlage-2025.9.0 )
	schluter? ( ~dev-python/py-schluter-0.1.7 )
	scrape? ( ~dev-python/beautifulsoup4-4.13.3 >=dev-python/lxml-6.0.1 )
	screenlogic? ( ~dev-python/screenlogicpy-0.10.2 )
	scsgate? ( ~dev-python/scsgate-0.1.0 )
	season? ( ~dev-python/ephem-4.1.6 )
	sendgrid? ( ~dev-python/sendgrid-6.8.2 )
	sense? ( ~dev-python/sense-energy-0.13.8 )
	sensibo? ( ~dev-python/pysensibo-1.2.1 )
	sensirion-ble? ( ~dev-python/sensirion-ble-0.1.1 )
	sensorpro? ( ~dev-python/sensorpro-ble-0.7.1 )
	sensorpush-cloud? ( ~dev-python/sensorpush-api-2.1.3 ~dev-python/sensorpush-ha-1.3.2 )
	sensorpush? ( ~dev-python/sensorpush-ble-1.9.0 )
	sensoterra? ( ~dev-python/sensoterra-2.0.1 )
	sentry? ( ~dev-python/sentry-sdk-2.48.0 )
	senz? ( ~dev-python/pysenz-1.0.2 )
	serial? ( ~dev-python/pyserial-asyncio-fast-0.16 )
	serial-pm? ( ~dev-python/pmsensor-0.4 )
	sesame? ( ~dev-python/pysesame2-1.0.1 )
	seven-segments? ( ~dev-python/pillow-12.1.1 )
	seventeentrack? ( ~dev-python/pyseventeentrack-1.1.1 )
	sfr-box? ( ~dev-python/sfrbox-api-0.1.0 )
	sftp-storage? ( ~dev-python/asyncssh-2.21.0 )
	sharkiq? ( ~dev-python/sharkiq-1.5.0 )
	shelly? ( ~dev-python/aioshelly-13.23.1 )
	shodan? ( ~net-analyzer/shodan-1.28.0 )
	sia? ( ~dev-python/pysiaalarm-3.2.2 )
	sighthound? ( ~dev-python/pillow-12.1.1 ~dev-python/simplehound-0.3 )
	signal-messenger? ( ~dev-python/pysignalclirestapi-0.3.24 )
	simplefin? ( ~dev-python/simplefin4py-0.0.18 )
	simplepush? ( ~dev-python/simplepush-2.2.3 )
	simplisafe? ( ~dev-python/simplisafe-python-2024.1.0 )
	sinch? ( ~dev-python/clx-sdk-xms-1.0.0 )
	sisyphus? ( ~dev-python/sisyphus-control-3.1.4 )
	skybeacon? ( ~dev-python/pygatt-4.0.5[GATTTOOL] )
	skybell? ( ~dev-python/aioskybell-22.7.0 )
	sky-hub? ( ~dev-python/pyskyqhub-0.1.4 )
	sky-remote? ( ~dev-python/skyboxremote-0.0.6 )
	slack? ( ~dev-python/aiofiles-24.1.0 ~dev-python/slack-sdk-3.33.4 )
	sleepiq? ( ~dev-python/asyncsleepiq-1.7.0 )
	slide-local? ( ~dev-python/goslide-api-0.7.0 )
	slide? ( ~dev-python/goslide-api-0.7.0 )
	slimproto? ( ~dev-python/aioslimproto-3.0.0 )
	sma? ( ~dev-python/pysma-1.1.0 )
	smappee? ( ~dev-python/pysmappee-0.2.29 )
	smarla? ( ~dev-python/pysmarlaapi-1.0.1 )
	smart-meter-texas? ( ~dev-python/smart-meter-texas-0.5.5 )
	smartthings? ( ~dev-python/pysmartthings-3.7.0 )
	smarttub? ( ~dev-python/python-smarttub-0.0.47 )
	smarty? ( ~dev-python/pysmarty2-0.10.3 )
	smhi? ( ~dev-python/pysmhi-1.1.0 )
	smlight? ( ~dev-python/pysmlight-0.2.16 )
	snapcast? ( ~dev-python/snapcast-2.3.7 )
	snmp? ( ~dev-python/pysnmp-7.1.22 )
	snoo? ( ~dev-python/python-snoo-0.8.3 )
	snooz? ( ~dev-python/pysnooz-0.8.6 )
	solaredge-local? ( ~dev-python/solaredge-local-0.2.3 )
	solaredge? ( ~dev-python/aiosolaredge-0.2.0 ~dev-python/solaredge-web-0.0.1 )
	solarlog? ( ~dev-python/solarlog-cli-0.7.0 )
	solax? ( ~dev-python/solax-3.2.3 )
	soma? ( ~dev-python/pysoma-0.0.12 )
	somfy-mylink? ( ~dev-python/somfy-mylink-synergy-1.0.6 )
	sonarr? ( ~dev-python/aiopyarr-23.4.0 )
	songpal? ( ~dev-python/python-songpal-0.16.2 )
	sonos? ( =dev-python/defusedxml-0.7.1-r1 ~dev-python/soco-0.30.14 ~dev-python/sonos-websocket-0.1.3 )
	sony-projector? ( ~dev-python/pysdcp-1 )
	soundtouch? ( >=dev-python/libsoundtouch-0.8.0 )
	spc? ( ~dev-python/pyspcwebgw-0.7.0 )
	speedtestdotnet? ( ~net-analyzer/speedtest-cli-2.1.3 )
	splunk? ( ~dev-python/hass-splunk-0.1.4 )
	spotify? ( ~dev-python/spotifyaio-2.0.2 )
	sql? ( ~dev-python/sqlalchemy-2.0.41 ~dev-python/sqlparse-0.5.5 )
	squeezebox? ( ~dev-python/pysqueezebox-0.13.0 )
	srp-energy? ( ~dev-python/srpenergy-1.3.6 )
	ssdp? ( ~dev-python/async-upnp-client-0.46.2 )
	starline? ( ~dev-python/starline-0.1.5 )
	starlingbank? ( ~dev-python/starlingbank-3.2 )
	starlink? ( ~dev-python/starlink-grpc-core-1.2.3 )
	startca? ( ~dev-python/xmltodict-1.0.2 )
	statsd? ( ~dev-python/statsd-3.2.1 )
	steamist? ( ~dev-python/aiosteamist-1.0.1 ~dev-python/discovery30303-0.3.3 )
	steam-online? ( ~dev-python/steamodd-4.21 )
	stiebel-eltron? ( ~dev-python/pystiebeleltron-0.2.5 )
	stookwijzer? ( ~dev-python/stookwijzer-1.6.1 )
	streamlabswater? ( ~dev-python/streamlabswater-1.0.1 )
	stream? ( ~dev-python/pyturbojpeg-1.8.0 ~dev-python/av-16.0.1 ~dev-python/numpy-2.3.2 )
	subaru? ( ~dev-python/subarulink-0.7.15 )
	suez-water? ( ~dev-python/pysuezv2-2.0.7 )
	sunricher-dali? ( ~dev-python/pysrdaligateway-0.19.3 )
	supla? ( ~dev-python/asyncpysupla-0.0.5 )
	surepetcare? ( ~dev-python/surepy-0.9.0 )
	swiss-hydrological-data? ( ~dev-python/swisshydrodata-0.1.0 )
	swiss-public-transport? ( ~dev-python/python-opendata-transport-0.5.0 )
	switchbee? ( ~dev-python/pyswitchbee-1.8.3 )
	switchbot-cloud? ( ~dev-python/switchbot-api-2.10.0 )
	switchbot? ( ~dev-python/pyswitchbot-1.0.0 )
	switcher-kis? ( ~dev-python/aioswitcher-6.1.1 )
	switchmate? ( ~dev-python/pyswitchmate-0.5.1 )
	syncthing? ( ~dev-python/aiosyncthing-0.7.1 )
	syncthru? ( ~dev-python/pysyncthru-0.8.0 ~dev-python/url-normalize-2.2.1 )
	synology-dsm? ( ~dev-python/py-synologydsm-api-2.7.3 )
	synology-srm? ( ~dev-python/synology-srm-0.2.0 )
	system-bridge? ( ~dev-python/systembridgeconnector-5.4.3 )
	systemmonitor? ( ~dev-python/psutil-home-assistant-0.0.1 ~dev-python/psutil-7.1.2 )
	systemnexa2? ( ~dev-python/python-sn2-0.4.0 )
	tado? ( ~dev-python/python-tado-0.18.16 )
	tailscale? ( ~dev-python/tailscale-0.6.2 )
	tailwind? ( ~dev-python/gotailwind-0.3.0 )
	tami4? ( ~dev-python/tami4edgeapi-3.0 )
	tankerkoenig? ( ~dev-python/aiotankerkoenig-0.5.1 )
	tank-utility? ( ~dev-python/tank-utility-1.5.0 )
	tapsaff? ( ~dev-python/tapsaff-0.2.1 )
	tasmota? ( ~dev-python/hatasmota-0.10.1 )
	tautulli? ( ~dev-python/pytautulli-23.1.1 )
	technove? ( ~dev-python/python-technove-2.0.0 )
	ted5000? ( ~dev-python/xmltodict-1.0.2 )
	tedee? ( ~dev-python/aiotedee-0.2.25 )
	telegram-bot? ( ~dev-python/python-telegram-bot-22.1[socks] )
	tellduslive? ( ~dev-python/tellduslive-0.10.12 )
	tellstick? ( ~dev-python/tellcore-net-0.4 ~dev-python/tellcore-py-1.1.2 )
	teltonika? ( ~dev-python/teltasync-0.2.0 )
	temper? ( ~dev-python/temperusb-1.6.1 )
	tesla-fleet? ( ~dev-python/tesla-fleet-api-1.4.3 )
	tesla-wall-connector? ( ~dev-python/tesla-wall-connector-1.1.0 )
	teslemetry? ( ~dev-python/tesla-fleet-api-1.4.3 ~dev-python/teslemetry-stream-0.9.0 )
	tessie? ( ~dev-python/tesla-fleet-api-1.4.3 ~dev-python/tessie-api-0.1.1 )
	thermobeacon? ( ~dev-python/thermobeacon-ble-0.10.0 )
	thermopro? ( ~dev-python/thermopro-ble-1.1.3 )
	thethingsnetwork? ( ~dev-python/ttn-client-1.2.3 )
	thingspeak? ( ~dev-python/thingspeak-1.0.0 )
	thinkingcleaner? ( ~dev-python/pythinkingcleaner-0.0.3 )
	thread? ( ~dev-python/pyroute2-0.7.5 ~dev-python/python-otbr-api-2.9.0 )
	tibber? ( ~dev-python/pytibber-0.36.0 )
	tikteck? ( ~dev-python/tikteck-0.4 )
	tile? ( ~dev-python/pytile-2024.12.0 )
	tilt-ble? ( ~dev-python/tilt-ble-1.0.1 )
	tilt-pi? ( ~dev-python/tilt-pi-0.2.1 )
	tmb? ( ~dev-python/tmb-0.0.4 )
	todoist? ( ~dev-python/todoist-api-python-3.1.0 )
	togrill? ( ~dev-python/togrill-bluetooth-0.8.1 )
	tolo? ( ~dev-python/tololib-1.2.2 )
	tomorrowio? ( ~dev-python/pytomorrowio-0.3.6 )
	toon? ( ~dev-python/toonapi-0.3.0 )
	totalconnect? ( ~dev-python/total-connect-client-2025.12.2 )
	touchline? ( ~dev-python/pytouchline-extended-0.4.5 )
	touchline-sl? ( ~dev-python/pytouchlinesl-0.6.0 )
	tplink-lte? ( ~dev-python/tp-connected-0.0.4 )
	tplink? ( ~dev-python/python-kasa-0.10.2[speedups] )
	tplink-omada? ( ~dev-python/tplink-omada-client-1.5.3 )
	traccar? ( ~dev-python/pytraccar-3.0.0 )
	traccar-server? ( ~dev-python/pytraccar-3.0.0 )
	tractive? ( ~dev-python/aiotractive-1.0.0 )
	tradfri? ( ~dev-python/pytradfri-9.0.1[async] )
	trafikverket-camera? ( ~dev-python/pytrafikverket-1.1.1 )
	trafikverket-ferry? ( ~dev-python/pytrafikverket-1.1.1 )
	trafikverket-train? ( ~dev-python/pytrafikverket-1.1.1 )
	trafikverket-weatherstation? ( ~dev-python/pytrafikverket-1.1.1 )
	trane? ( ~dev-python/steamloop-1.2.0 )
	transmission? ( ~dev-python/transmission-rpc-7.0.3 )
	transport-nsw? ( ~dev-python/pytransportnsw-0.1.1 )
	travisci? ( ~dev-python/travispy-0.3.5 )
	trend? ( ~dev-python/numpy-2.3.2 )
	triggercmd? ( ~dev-python/triggercmd-0.0.36 )
	tts? ( ~media-libs/mutagen-1.47.0 )
	tuya? ( ~dev-python/tuya-device-handlers-0.0.10 ~dev-python/tuya-device-sharing-sdk-0.2.8 )
	twentemilieu? ( ~dev-python/twentemilieu-2.2.1 )
	twilio? ( ~dev-python/twilio-6.32.0 )
	twinkly? ( ~dev-python/ttls-1.8.3 )
	twitch? ( ~dev-python/twitchapi-4.2.1 )
	twitter? ( ~dev-python/twitterapi-2.7.12 )
	ubus? ( ~dev-python/openwrt-ubus-rpc-0.0.2 )
	uhoo? ( ~dev-python/uhooapi-1.2.6 )
	ukraine-alarm? ( ~dev-python/uasiren-0.0.1 )
	unifi-direct? ( ~dev-python/unifi-ap-0.0.2 )
	unifiled? ( ~dev-python/unifiled-0.11 )
	unifi? ( ~dev-python/aiounifi-88 )
	unifiprotect? ( ~dev-python/uiprotect-10.2.2 ~dev-python/unifi-discovery-1.2.0 )
	upb? ( ~dev-python/upb-lib-0.6.1 )
	upc-connect? ( ~dev-python/connect-box-0.3.1 )
	upcloud? ( ~dev-python/upcloud-api-2.9.0 )
	upnp? ( ~dev-python/async-upnp-client-0.46.2 ~dev-python/getmac-0.9.5 )
	uptime-kuma? ( ~dev-python/pythonkuma-0.5.0 )
	uptimerobot? ( ~dev-python/pyuptimerobot-24.0.1 )
	usb? ( ~dev-python/aiousbwatcher-1.1.1 ~dev-python/pyserial-3.5 )
	usgs-earthquakes-feed? ( ~dev-python/aio-geojson-usgs-earthquakes-0.3 )
	utility-meter? ( ~dev-python/cronsim-2.7 )
	uvc? ( ~dev-python/uvcclient-0.12.1 )
	v2c? ( ~dev-python/pytrydan-0.8.0 )
	vallox? ( ~dev-python/vallox-websocket-api-6.0.0 )
	vasttrafik? ( ~dev-python/vtjp-0.2.1 )
	vegehub? ( ~dev-python/vegehub-0.1.26 )
	velbus? ( ~dev-python/velbus-aio-2026.2.0 )
	velux? ( ~dev-python/pyvlx-0.2.30 )
	venstar? ( ~dev-python/venstarcolortouch-0.21 )
	vera? ( ~dev-python/pyvera-0.3.16 )
	verisure? ( ~dev-python/vsure-2.6.7 )
	versasense? ( ~dev-python/pyversasense-0.0.6 )
	version? ( ~dev-python/pyhaversion-22.8.0 )
	vesync? ( ~dev-python/pyvesync-3.4.1 )
	viaggiatreno? ( ~dev-python/viaggiatreno-ha-0.2.4 )
	vicare? ( ~dev-python/pyvicare-2.58.0 )
	victron-ble? ( ~dev-python/victron-ble-ha-parser-0.4.10 )
	victron-remote-monitoring? ( ~dev-python/victron-vrm-0.1.8 )
	vilfo? ( ~dev-python/vilfo-api-client-0.5.0 )
	vivotek? ( ~dev-python/libpyvivotek-0.6.1 )
	vizio? ( ~dev-python/pyvizio-0.1.61 )
	vlc? ( ~dev-python/python-vlc-3.0.18122 )
	vlc-telnet? ( ~dev-python/aiovlc-0.5.1 )
	vodafone-station? ( ~dev-python/aiovodafone-3.1.3 )
	voip? ( ~dev-python/voip-utils-0.3.5 )
	volkszaehler? ( ~dev-python/volkszaehler-0.4.0 )
	volumio? ( ~dev-python/pyvolumio-0.1.5 )
	volvo? ( ~dev-python/volvocarsapi-0.4.3 )
	w800rf32? ( ~dev-python/pyw800rf32-0.4 )
	wake-on-lan? ( ~dev-python/wakeonlan-3.1.0 )
	wallbox? ( ~dev-python/wallbox-0.9.0 )
	waqi? ( ~dev-python/aiowaqi-3.1.0 )
	waterfurnace? ( ~dev-python/waterfurnace-1.5.1 )
	watergate? ( ~dev-python/watergate-local-api-2025.1.0 )
	watts? ( ~dev-python/visionpluspython-1.0.2 )
	watttime? ( ~dev-python/aiowatttime-0.1.1 )
	waze-travel-time? ( ~dev-python/pywaze-1.1.1 )
	weatherflow-cloud? ( ~dev-python/weatherflow4py-1.4.1 )
	weatherflow? ( ~dev-python/pyweatherflowudp-1.5.0 )
	weatherkit? ( ~dev-python/apple-weatherkit-1.1.3 )
	webdav? ( ~dev-python/aiowebdav2-0.6.1 )
	webmin? ( ~dev-python/webmin-xmlrpc-0.0.2 )
	webostv? ( ~dev-python/aiowebostv-0.7.5 )
	weheat? ( ~dev-python/weheat-2026.2.28 )
	wemo? ( ~dev-python/pywemo-1.4.0 )
	whirlpool? ( ~dev-python/whirlpool-sixth-sense-1.0.3 )
	whois? ( ~dev-python/whois-0.9.27 )
	wiffi? ( ~dev-python/wiffi-1.1.2 )
	wilight? ( ~dev-python/pywilight-0.0.74 )
	wirelesstag? ( ~dev-python/wirelesstagpy-0.8.1 )
	withings? ( ~dev-python/aiowithings-3.1.6 )
	wiz? ( ~dev-python/pywizlight-0.6.3 )
	wled? ( ~dev-python/wled-0.21.0 )
	wmspro? ( ~dev-python/pywmspro-0.3.3 )
	wolflink? ( ~dev-python/wolf-comm-0.0.23 )
	workday? ( ~dev-python/holidays-0.84 )
	ws66i? ( ~dev-python/pyws66i-1.1 )
	wsdot? ( ~dev-python/wsdot-0.0.1 )
	wyoming? ( ~dev-python/wyoming-1.7.2 )
	xbox? ( ~dev-python/python-xbox-0.1.3 )
	xeoma? ( ~dev-python/pyxeoma-1.4.2 )
	xiaomi-aqara? ( ~dev-python/pyxiaomigateway-0.14.3 )
	xiaomi-ble? ( ~dev-python/xiaomi-ble-1.6.0 )
	xiaomi-miio? ( ~dev-python/construct-2.10.68 ~dev-python/micloud-0.5 ~dev-python/python-miio-0.5.12 )
	xiaomi-tv? ( ~dev-python/pymitv-1.4.3 )
	xmpp? ( ~dev-python/emoji-2.8.0 ~dev-python/slixmpp-1.13.2 )
	xs1? ( ~dev-python/xs1-api-client-3.0.0 )
	yale? ( ~dev-python/yalexs-ble-3.2.8 ~dev-python/yalexs-9.2.0 )
	yale-smart-alarm? ( ~dev-python/yalesmartalarmclient-0.4.3 )
	yalexs-ble? ( ~dev-python/yalexs-ble-3.2.8 )
	yamaha? ( ~dev-python/rxv-0.7.0 )
	yamaha-musiccast? ( ~dev-python/aiomusiccast-0.15.0 )
	yandex-transport? ( ~dev-python/aioymaps-1.2.5 )
	yardian? ( ~dev-python/pyyardian-1.1.1 )
	yeelight? ( ~dev-python/async-upnp-client-0.46.2 ~dev-python/yeelight-0.7.16 )
	yeelightsunflower? ( ~dev-python/yeelightsunflower-0.0.10 )
	yi? ( ~dev-python/aioftp-0.21.3 )
	yolink? ( ~dev-python/yolink-api-0.6.1 )
	youless? ( ~dev-python/youless-api-2.2.0 )
	youtube? ( ~dev-python/youtubeaio-2.1.1 )
	zabbix? ( ~dev-python/zabbix-utils-2.0.3 )
	zamg? ( ~dev-python/zamg-0.3.6 )
	zeroconf? ( ~dev-python/zeroconf-0.148.0 )
	zerproc? ( ~dev-python/pyzerproc-0.4.8 )
	zestimate? ( ~dev-python/xmltodict-1.0.2 )
	zeversolar? ( ~dev-python/zeversolar-0.3.2 )
	zha? ( ~dev-python/serialx-0.6.2 ~dev-python/zha-1.0.2 )
	zhong-hong? ( ~dev-python/zhong-hong-hvac-1.0.13 )
	ziggo-mediabox-xl? ( ~dev-python/ziggo-mediabox-xl-1.1.0 )
	zimi? ( ~dev-python/zcc-helper-3.7 )
	zinvolt? ( ~dev-python/zinvolt-0.3.0 )
	zoneminder? ( ~dev-python/zm-py-0.5.4 )
	zwave-js? ( ~dev-python/pyserial-3.5 ~dev-python/zwave-js-server-python-0.68.0 )
	zwave-me? ( ~dev-python/url-normalize-2.2.1 ~dev-python/zwave-me-ws-0.4.3 )
"

BDEPEND="${RDEPEND}
	test? (
		dev-python/astroid
		dev-python/coverage
		dev-python/freezegun
		dev-python/mock-open
		dev-python/mypy-dev
		dev-python/pipdeptree
		dev-vcs/pre-commit
		dev-python/pylint-per-file-ignores
		dev-python/pylint
		dev-python/pytest-asyncio
		dev-python/pytest-cov
		dev-python/pytest-freezer
		dev-python/pytest-github-actions-annotate-failures
		dev-python/pytest-picked
		dev-python/pytest-socket
		dev-python/pytest-sugar
		dev-python/pytest-timeout
		dev-python/pytest-unordered
		dev-python/pytest-xdist
		dev-python/pytest
		dev-python/requests-mock
		dev-python/respx
		dev-python/syrupy
		dev-python/tqdm
	)
"

src_prepare() {
	if use test ; then
		cp --no-preserve=mode --recursive "${WORKDIR}/core-${MY_PV}/tests" "${S}"
		chmod u+x "${S}/tests/auth/providers/test_command_line_cmd.sh"
	fi
	sed -E -i "s/regex==[^ ]*/regex/g" -i "homeassistant/package_constraints.txt" || die

	distutils-r1_src_prepare
}
INSTALL_DIR="/opt/${MY_PN}"

DISABLE_AUTOFORMATTING=1
DOC_CONTENTS="
The HA interface listens on port 8123
hass configuration is in: /etc/${MY_PN}
daemon command line arguments are configured in: /etc/conf.d/${MY_PN}
logging is to: /var/log/${MY_PN}/{server,errors,stdout}.log
The sqlite db is by default in: /etc/${MY_PN}
support at https://git.edevau.net/onkelbeh/HomeAssistantRepository
"

DOCS="README.rst"

python_install_all() {
	dodoc ${DOCS}
	distutils-r1_python_install_all
	keepdir "$INSTALL_DIR"
	keepdir "/etc/${MY_PN}"
	fowners -R "${MY_PN}:${MY_PN}" "/etc/${MY_PN}"
	keepdir "/var/log/${MY_PN}"
	fowners -R "${MY_PN}:${MY_PN}" "/var/log/${MY_PN}"
	newconfd "${FILESDIR}/${MY_PN}.conf.d" "${MY_PN}"
	newinitd "${FILESDIR}/${MY_PN}.init.d" "${MY_PN}"
	use systemd && systemd_dounit "${FILESDIR}/${MY_PN}.service"
	dobin "${FILESDIR}/hasstest"
	if use socat ; then
		newinitd "${FILESDIR}/socat-zwave.init.d" "socat-zwave"
		sed -i -e 's/# need socat-zwave/need socat-zwave/g' "${D}/etc/init.d/${MY_PN}" || die
	fi
	if use mqtt ; then
		sed -i -e 's/# need mosquitto/need mosquitto/g' "${D}/etc/init.d/${MY_PN}" || die
	fi
	if use cli ; then
		echo -e "stop() {\n\tebegin Stoping homeassistant\n\thass-cli --token \${HASS_TOKEN} -s \${HASS_SERVER} service call homeassistant.stop\n\tsleep .5\n\tstart-stop-daemon -K \$command --pidfile \$pidfile\n\teend\n}" >> "${D}/etc/init.d/${MY_PN}"
	fi
	insinto /etc/logrotate.d
	newins "${FILESDIR}/${MY_PN}.logrotate" "${MY_PN}"
	readme.gentoo_create_doc
}

pkg_postinst() {
	readme.gentoo_print_elog
}

distutils_enable_tests pytest
