# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

DESCRIPTION="Homeassistant features set"

SLOT="0"
KEYWORDS="amd64 arm arm64 x86"
IUSE="+minimal normal full"
REQUIRED_USE=" ^^ ( minimal normal full ) "
RDEPEND="
	minimal? ( app-misc/homeassistant[accuweather,airly,airvisual,alpha-vantage,analytics-insights,androidtv,androidtv-remote,android-ip-webcam,axis,backup,bluetooth,caldav,camera,cast,cli,co2signal,compensation,coronavirus,dlna-dmr,dlna-dms,dwd-weather-warnings,ecowitt,enigma2,esphome,ffmpeg,file,forecast-solar,fronius,github,glances,holiday,homekit,homekit-controller,http,hyperion,ibeacon,influxdb,knx,kodi,kraken,local-calendar,local-todo,mariadb,matter,maxcube,mikrotik,mobile-app,modbus,mosquitto,mqtt,mysensors,mysql,nextcloud,nfandroidtv,notify-events,octoprint,onvif,openweathermap,otp,owntracks,ping,plex,ps4,python-script,qnap,qvr-pro,radio-browser,recorder,rest,ring,ruuvi-gateway,samsungtv,scrape,season,shelly,signal-messenger,snmp,socat,sonos,speedtestdotnet,spotify,sql,ssl,systemmonitor,tankerkoenig,tile,tomorrowio,tplink,upnp,utility-meter,version,wake-on-lan,waze-travel-time,wemo,whois,wled,workday,xiaomi-aqara,yamaha,yamaha-musiccast,zeroconf,zha,zwave-js] )

	normal? ( app-misc/homeassistant[abode,accuweather,acer-projector,acmeda,adguard,ads,aftership,agent-dvr,airly,airvisual,alarmdecoder,ambient-station,amcrest,ampio,analytics-insights,androidtv,androidtv-remote,android-ip-webcam,anthemav,apache-kafka,apcupsd,apple-tv,apprise,aquostv,arcam-fmj,aruba,asuswrt,aten-pe,atome,august,aurora-abb-powerone,avea,avion,awair,axis,backup,baidu,beewi-smartclim,bh1750,bitcoin,bizkaibus,blackbird,blebox,blink,blinkt,blockchain,bluetooth,bme280,bmw-connected-drive,bond,braviatv,bring,broadlink,brottsplatskartan,brunt,bsblan,bt-home-hub-5,bt-smarthub,buienradar,caldav,camera,canary,cast,cisco-mobility-express,cli,co2signal,compensation,coronavirus,daikin,deconz,delijn,denonavr,deutsche-bahn,devolo-home-control,dexcom,dhcp,dht,discogs,discord,dlna-dmr,dlna-dms,doorbird,dunehd,dwd-weather-warnings,dynalite,ecobee,ecowitt,emulated-roku,enigma2,enocean,enphase-envoy,environment-canada,esphome,everlights,evohome,ffmpeg,fibaro,file,flume,flux-led,foobot,forecast-solar,fortios,freebox,fritz,fritzbox,fritzbox-callmonitor,fronius,gios,github,glances,gogogate2,greeneye-monitor,growatt-server,guardian,harman-kardon-avr,harmony,heos,here-travel-time,holiday,homekit,homekit-controller,homematic,homematicip-cloud,hp-ilo,http,hue,hydrawise,iaqualink,ibeacon,ihc,image-upload,imap,incomfort,influxdb,insteon,intesishome,ipma,ipp,islamic-prayer-times,jewish-calendar,joaoapps-join,kef,knx,kodi,kraken,lifx,linode,litterrobot,local-calendar,local-todo,luci,luftdaten,mariadb,matter,maxcube,media-extractor,met,meteo-france,mfi,mikrotik,mobile-app,modbus,mosquitto,mqtt,mysql,nad,nederlandse-spoorwegen,netatmo,netdata,nextcloud,nfandroidtv,nmap-tracker,notify-events,nuki,nut,nws,nx584,octoprint,onkyo,onvif,opengarage,opensensemap,openweathermap,opnsense,otp,owntracks,panasonic-viera,philips-js,pilight,ping,pi-hole,plex,plugwise,poolsense,powerwall,ps4,python-script,qnap,qvr-pro,rachio,radio-browser,rainbird,rainmachine,recorder,rejseplanen,rest,ring,roku,roomba,roon,ruuvi-gateway,samsungtv,scrape,season,shelly,shodan,signal-messenger,simplisafe,skybell,sma,smappee,smartthings,snmp,socat,solax,somfy,sonos,speedtestdotnet,spotify,sql,squeezebox,ssl,statsd,synology-dsm,systemmonitor,tankerkoenig,tellduslive,tesla,tile,tomorrowio,toon,totalconnect,tplink,tts,tuya,unifi,unifi-direct,upnp,usb,utility-meter,vallox,velbus,velux,vera,version,vicare,vizio,wake-on-lan,waqi,waze-travel-time,webostv,wemo,whois,wink,withings,wled,workday,xbox,xiaomi-aqara,xiaomi-miio,xiaomi-tv,xs1,yamaha,yamaha-musiccast,yeelight,yi,zeroconf,zerproc,zha,zhong-hong,zoneminder,zwave-js] )

	full? (
		app-misc/homeassistant[bh1750,blinkt,bme280,cli,coronavirus,deutsche-bahn,dht,http,mariadb,mosquitto,mysql,socat,somfy,tesla,wink]
		app-misc/homeassistant[abode,acaia,accuweather,acer-projector,acmeda,actron-air,adax,adguard,ads,advantage-air,aemet,aftership,agent-dvr,airgradient,airly,airnow,airpatrol,airq,airthings,airthings-ble,airtouch4,airtouch5,airvisual,airobot,airos,airvisual-pro,airzone-cloud,airzone,aladdin-connect,alarmdecoder,alexa-devices,alpha-vantage,altruist,amazon-polly,amberelectric,ambient-network,ambient-station,amcrest,ampio,analytics-insights,android-ip-webcam,androidtv,androidtv-remote,anel-pwrctrl,anglian-water,anova,anthemav,anthropic,aosmith,apache-kafka,apcupsd,apple-tv,apprise,aprilaire,aprs,apsystems,aquacell,aqualogic,aquostv,aranet,arcam-fmj,arris-tg2492lg,aruba,arve,aseko-pool-live,assist-pipeline,asuswrt,assist-satellite,atag,aten-pe,atome,august,aurora-abb-powerone,aurora,aussie-broadband,autarco,avea,avion,awair,aws,aws-s3,axis,azure-data-explorer,azure-devops,azure-event-hub,azure-service-bus,azure-storage]
		app-misc/homeassistant[backblaze-b2,backup,baf,baidu,balboa,bang-olufsen,bbox,beewi-smartclim,bitcoin,bizkaibus,blackbird,blebox,blink,blockchain,blue-current,bluemaestro,bluesound,bluetooth,bmw-connected-drive,bond,bosch-alarm,bosch-shc,braviatv,bring,broadlink,brother,brottsplatskartan,brunt,bryant-evolution,bsblan,bt-home-hub-5,bthome,bt-smarthub,buienradar]
		app-misc/homeassistant[caldav,cambridge-audio,camera,canary,cast,ccm15,chacon-dio,channels,cisco-ios,cisco-mobility-express,cisco-webex-teams,citybikes,clementine,cloudflare,cloudflare-r2,cloud,cmus,co2signal,coinbase,color-extractor,comelit,comfoconnect,command-line,compensation,compit,concord232,control4,conversation,cookidoo,coolmaster,cppm-tracker,cpuspeed,crownstone,cync]
		app-misc/homeassistant[daikin,danfoss-air,datadog,deako,debugpy,deconz,decora-wifi,delijn,deluge,denonavr,devialet,devolo-home-control,devolo-home-network,dexcom,dhcp,digital-ocean,directv,discogs,discord,discovergy,dlink,dlna-dmr,dlna-dms,dnsip,doods,doorbird,dormakaba-dkey,dremel-3d-printer,drop-connect,droplet,dsmr,duke-energy,dunehd,duotecno,dwd-weather-warnings,dynalite]
		app-misc/homeassistant[eafm,easyenergy,ebox,ebusd,ecoal-boiler,ecobee,ecoforest,econet,ecovacs,ecowitt,edimax,edl21,efergy,egardia,eheimdigital,ekeybionyx,electrasmart,electric-kiwi,elevenlabs,elgato,egauge,eliqonline,elkm1,elmax,elvia,elv,emby,emoncms,emoncms-history,emonitor,emulated-kasa,emulated-roku,energenie-power-sockets,energyid,energyzero,enigma2,enocean,enphase-envoy,entur-public-transport,environment-canada,envisalink,ephember,epic-games-store,epion,epson,eq3btsmart,escea,esphome,essent,etherscan,eufylife-ble,eufy,everlights,evil-genius-labs,evohome,ezviz]
		app-misc/homeassistant[faa-delays,familyhub,fastdotcom,feedreader,ffmpeg,fibaro,fido,file,fing,fints,firefly-iii,fireservicerota,firmata,fish-audio,fitbit,fivem,fixer,fjaraskupan,fleetgo,flexit-bacnet,flic,flipr,flo,flume,fluss,flux-led,folder-watcher,foobot,forecast-solar,forked-daapd,fortios,foscam,freebox,freedompro,free-mobile,fressnapf-tracker,fritzbox-callmonitor,fritzbox,fritz,fronius,frontend,frontier-silicon,fujitsu-fglair,fully-kiosk,futurenow,fyta]
		app-misc/homeassistant[garages-amsterdam,gardena-bluetooth,gc100,gdacs,generic,geniushub,gentex-homelink,geocaching,geo-json-events,geonetnz-quakes,geonetnz-volcano,geo-rss-events,gios,github,gitlab-ci,gitter,glances,go2rtc,goalzero,gogogate2,goodwe,google-air-quality,google-assistant-sdk,google-cloud,google-drive,google-generative-ai-conversation,google-mail,google,google-maps,google-photos,google-pubsub,google-sheets,google-tasks,google-translate,google-travel-time,google-weather,govee-ble,govee-light-local,gpsd,gree,green-planet-energy,greeneye-monitor,greenwave,growatt-server,gtfs,guardian]
		app-misc/homeassistant[habitica,hanna,hardware,harman-kardon-avr,harmony,hassio,hdfury,hdmi-cec,heatmiser,heos,here-travel-time,hikvisioncam,hikvision,hisense-aehw4a1,hive,hko,hlk-sw16,holiday,homeassistant-hardware,home-connect,homee,homekit-controller,homekit,homematicip-cloud,homematic,homewizard,homeworks,honeywell,horizon,hp-ilo,html5,huawei-lte,hue,hue-ble,huisbaasje,hunterdouglas-powerview,husqvarna-automower-ble,husqvarna-automower,huum,hvv-departures,hydrawise,hyperion]
		app-misc/homeassistant[ialarm,iammeter,iaqualink,ibeacon,icloud,idasen-desk,idteck-prox,ifttt,iglo,igloohome,ign-sismologia,ihc,image-upload,imap,imeon-inverter,imgw-pib,immich,improv-ble,incomfort,inels,influxdb,inkbird,insteon,intellifire,intesishome,iometer,iotawatt,iotty,iperf3,ipma,ipp,iqvia,irish-rail-transport,irm-kmi,iron-os,isal,iskra,islamic-prayer-times,israel-rail,iss,ista-ecotrend,isy994,itach,ituran,izone]
		app-misc/homeassistant[jellyfin,jewish-calendar,joaoapps-join,justnimbus,jvc-projector]
		app-misc/homeassistant[kaiterra,kaleidescape,keba,keenetic-ndms2,kef,kegtron,keyboard-remote,keymitt-ble,kira,kiwi,kmtronic,knocki,knx,kodi,konnected,kostal-plenticore,kraken,kulersky,kwb]
		app-misc/homeassistant[lacrosse,lacrosse-view,lamarzocco,lametric,landisgyr-heat-meter,lastfm,launch-library,laundrify,lcn,ld2410-ble,leaone,led-ble,lektrico,letpot,lg-netcast,lg-soundbar,lg-thinq,libre-hardware-monitor,lidarr,lifx,lightwave,limitlessled,linkplay,linode,linux-battery,litejet,litterrobot,livisi,local-calendar,local-todo,london-underground,lookin,loqed,luci,luftdaten,lunatone,lupusec,lutron-caseta,lutron,lw12wifi,lyric]
		app-misc/homeassistant[madvr,mailgun,marytts,mastodon,matrix,matter,maxcube,mcp,mcp-server,mealie,meater,medcom-ble,media-extractor,mediaroom,melcloud,melissa,melnor,message-bird,met-eireann,meteoalarm,meteoclimatic,meteo-france,meteo-lt,met,metoffice,mfi,microbees,microsoft,miele,mikrotik,mill,minecraft-server,minio,moat,mobile-app,mochad,modbus,modem-callerid,modern-forms,moehlenhoff-alpha2,monarch-money,monoprice,monzo,mopeka,motionblinds-ble,motion-blinds,motioneye,motionmount,mpd,mqtt,msteams,mullvad,music-assistant,mutesync,mvglive,mysensors,mystrom,mythicbeastsdns,myuplink]
		app-misc/homeassistant[nad,nam,nanoleaf,nasweb,neato,nederlandse-spoorwegen,ness-alarm,nest,netatmo,netdata,netgear-lte,netgear,netio,network,neurio-energy,nexia,nextbus,nextcloud,nextdns,nfandroidtv,nibe-heatpump,nice-go,nightscout,niko-home-control,nilu,nina,nintendo-parental-controls,nissan-leaf,nmap-tracker,nmbs,noaa-tides,nobo-hub,nordpool,norway-air,notify-events,notion,nrgkick,nsw-fuel-station,nsw-rural-fire-service-feed,ntfy,nuheat,nuki,numato,nut,nws,nx584,nyt-games,nzbget]
		app-misc/homeassistant[oasa-telematics,obihai,octoprint,oem,ohmconnect,ohme,ollama,ombi,omnilogic,ondilo-ico,onedrive,onewire,onkyo,onvif,openai-conversation,openerz,openevse,openexchangerates,opengarage,openhome,open-meteo,openrgb,open-router,opensensemap,opensky,opentherm-gw,openuv,openweathermap,opnsense,opower,opple,oralb,oru,orvibo,osoenergy,osramlightify,otbr,otp,ourgroceries,overkiz,overseerr,ovo-energy,owntracks]
		app-misc/homeassistant[p1-monitor,palazzetti,panasonic-bluray,panasonic-viera,paperless-ngx,peblar,peco,pegel-online,pencom,permobil,pglab,philips-js,picnic,pi-hole,pilight,ping,pjlink,plaato,playstation-network,plex,plugwise,pocketcasts,point,pooldose,poolsense,portainer,powerfox,powerwall,prana,private-ble-device,probe-plus,profiler,progettihwsw,proliphix,prometheus,prosegur,prowl,proxmoxve,proxy,prusalink,ps4,pterodactyl,pulseaudio-loopback,pure-energie,purpleair,pushbullet,pushover,pvoutput,pvpc-hourly-pricing,pyload,python-script]
		app-misc/homeassistant[qbittorrent,qbus,qingping,qld-bushfire,qnap,qnap-qsw,qrcode,quantum-gateway,qvr-pro,qwikswitch]
		app-misc/homeassistant[rabbitair,rachio,radarr,radio-browser,radiotherm,rainbird,raincloud,rainforest-eagle,rainforest-raven,rainmachine,rapt-ble,raspyrfm,rdw,recollect-waste,recorder,recswitch,reddit,refoss,rehlko,rejseplanen,remember-the-milk,remote-calendar,remote-rpi-gpio,renault,renson,reolink,repetier,rest,rflink,rfxtrx,ridwell,ring,ripple,risco,rituals-perfume-genie,rmvtransport,roborock,rocketchat,roku,romy,roomba,roon,route53,route-b-smart-meter,rova,rpi-power,ruckus-unleashed,russound-rio,russound-rnet,ruuvi-gateway,ruuvitag-ble,rympro]
		app-misc/homeassistant[sabnzbd,saj,samsungtv,sanix,satel-integra,saunum,schlage,schluter,scrape,screenlogic,scsgate,season,sendgrid,sense,sensibo,sensirion-ble,sensorpro,sensorpush-cloud,sensorpush,sensoterra,sentry,senz,serial,serial-pm,sesame,seven-segments,seventeentrack,sfr-box,sftp-storage,sharkiq,shelly,shodan,sia,sighthound,signal-messenger,simplefin,simplepush,simplisafe,sinch,sisyphus,skybeacon,skybell,sky-hub,sky-remote,slack,sleepiq,slide-local,slide,slimproto,sma,smappee,smarla,smarthab,smart-meter-texas,smartthings,smarttub,smarty,smhi,smlight,snapcast,snmp,snoo,snooz,solaredge-local,solaredge,solarlog,solax,soma,somfy-mylink,sonarr,songpal,sonos,sony-projector,soundtouch,spc,speedtestdotnet,splunk,spotify,sql,squeezebox,srp-energy,ssdp,starline,starlingbank,starlink,startca,statsd,steamist,steam-online,stiebel-eltron,stookwijzer,streamlabswater,stream,subaru,suez-water,sunricher-dali,supla,surepetcare,swiss-hydrological-data,swiss-public-transport,switchbee,switchbot-cloud,switchbot,switcher-kis,switchmate,syncthing,syncthru,synology-dsm,synology-srm,system-bridge,systemmonitor]
		app-misc/homeassistant[tado,tailscale,tailwind,tami4,tankerkoenig,tank-utility,tapsaff,tasmota,tautulli,technove,ted5000,tedee,telegram-bot,tellduslive,tellstick,temper,tesla-fleet,tesla-wall-connector,teslemetry,tessie,thermobeacon,thermopro,thethingsnetwork,thingspeak,thinkingcleaner,thread,tibber,tikteck,tile,tilt-ble,tilt-pi,tmb,todoist,togrill,tolo,tomorrowio,toon,totalconnect,touchline,touchline-sl,tplink-lte,tplink,tplink-omada,traccar,traccar-server,tractive,tradfri,trafikverket-camera,trafikverket-ferry,trafikverket-train,trafikverket-weatherstation,transmission,transport-nsw,travisci,trend,triggercmd,tts,tuya,twentemilieu,twilio,twinkly,twitch,twitter]
		app-misc/homeassistant[ubus,uhoo,ukraine-alarm,unifi-direct,unifiled,unifi,unifiprotect,upb,upc-connect,upcloud,uptime-kuma,uptimerobot,usgs-earthquakes-feed,utility-meter,uvc]
		app-misc/homeassistant[v2c,vallox,vasttrafik,vegehub,velbus,velux,venstar,vera,verisure,versasense,version,vesync,viaggiatreno,vicare,victron-ble,victron-remote-monitoring,vilfo,vivotek,vizio,vlc,vlc-telnet,vodafone-station,voip,volkszaehler,volumio,volvo]
		app-misc/homeassistant[w800rf32,wake-on-lan,wallbox,waqi,waterfurnace,watergate,watts,watttime,waze-travel-time,weatherflow-cloud,weatherflow,weatherkit,webdav,webmin,webostv,weheat,wemo,whirlpool,whois,wiffi,wilight,wirelesstag,withings,wiz,wled,wmspro,wolflink,workday,ws66i,wsdot,wyoming]
		app-misc/homeassistant[xbox,xeoma,xiaomi-aqara,xiaomi-ble,xiaomi-miio,xiaomi-tv,xmpp,xs1]
		app-misc/homeassistant[yale,yale-smart-alarm,yalexs-ble,yamaha,yamaha-musiccast,yandex-transport,yardian,yeelight,yeelightsunflower,yi,yolink,youless,youtube]
		app-misc/homeassistant[zabbix,zamg,zerproc,zestimate,zeversolar,zha,zhong-hong,ziggo-mediabox-xl,zimi,zoneminder,zwave-js,zwave-me]
	)
"
