name: Create ebuild
on:
  workflow_dispatch:
  create: 
jobs:
  genebuild:
    runs-on: ubuntu-latest
    steps:
       # synchronys my own git
       - name: Checkout code
         uses: actions/checkout@v7         
       - name: Autogen ebuild
         run: |
           full_package=${GITHUB_REF#refs/heads/feature/}
           category=$( echo $full_package | cut -d/ -f1 )
           package=$( echo $full_package | cut -d/ -f2 | sed 's/-[0-9].*//' )
           version=$( echo $full_package | sed "s/${category}\\/${package}-//" )
           case "${category}/${package}" in
             app-misc/homeassitant)
               cp "$(find app-misc/homeassistant/files/ge*.patch | sort -rV | head -n1)" "app-misc/homeassistant/files/genebuild_${version}.patch"
               ./scripts/genebuild.sh -dm "${version}"
               ;;
             *) 
               ./scripts/generate-missing-deps.sh "${category}/${package}" upgrade "${version}"
               ./scripts/generate-missing-deps.sh "${category}/${package}" build
               ;;
           esac
           gh pr create -B "feature/${full_package}" -H "master" --title 'Merge ${full_package} into base_branch'
